<?php

use Illuminate\Database\Seeder;
use App\Blok;

class BlokTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Blok::create(["code" => strtoupper("ALBD 1"), "name" => strtoupper("ALBD 1"), "lokaliti_id" => "1"]);
        Blok::create(["code" => strtoupper("ALBD 2"), "name" => strtoupper("ALBD 2"), "lokaliti_id" => "1"]);
        Blok::create(["code" => strtoupper("ALBD 1 & ALBD 2"), "name" => strtoupper("ALBD 1 & ALBD 2"), "lokaliti_id" => "1"]);
        Blok::create(["code" => strtoupper("ARBD 2"), "name" => strtoupper("ARBD 2"), "lokaliti_id" => "1"]);
        Blok::create(["code" => strtoupper("ARBD 1(1D,1G,1F)"), "name" => strtoupper("ARBD 1(1D,1G,1F)"), "lokaliti_id" => "1"]);
        Blok::create(["code" => strtoupper("NCD 5A1"), "name" => strtoupper("NCD 5A1"), "lokaliti_id" => "1"]);
        Blok::create(["code" => strtoupper("NCD 3A"), "name" => strtoupper("NCD 3A"), "lokaliti_id" => "1"]);
        Blok::create(["code" => strtoupper("ARBD 1 1F"), "name" => strtoupper("ARBD 1 1F"), "lokaliti_id" => "1"]);
        Blok::create(["code" => strtoupper("ARBD 6"), "name" => strtoupper("ARBD 6"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 7A(A1,A2,A3,A4"), "name" => strtoupper("ARBD 7A(A1,A2,A3,A4"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 7 (B,C,D,E)"), "name" => strtoupper("ARBD 7 (B,C,D,E)"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 7"), "name" => strtoupper("ARBD 7"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 7B"), "name" => strtoupper("ARBD 7B"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 5"), "name" => strtoupper("ARBD 5"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 5A5"), "name" => strtoupper("ARBD 5A5"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 5A"), "name" => strtoupper("ARBD 5A"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 7A3"), "name" => strtoupper("ARBD 7A3"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 7A"), "name" => strtoupper("ARBD 7A"), "lokaliti_id" => "2"]);
        Blok::create(["code" => strtoupper("ARBD 5A2"), "name" => strtoupper("ARBD 5A2"), "lokaliti_id" => "3"]);
        Blok::create(["code" => strtoupper("ARBD 5A"), "name" => strtoupper("ARBD 5A"), "lokaliti_id" => "3"]);
        Blok::create(["code" => strtoupper("ARBD 1C"), "name" => strtoupper("ARBD 1C"), "lokaliti_id" => "3"]);
        Blok::create(["code" => strtoupper("ARBD 1(1D,1G,2F)"), "name" => strtoupper("ARBD 1(1D,1G,2F)"), "lokaliti_id" => "3"]);
        Blok::create(["code" => strtoupper("ARBD 3"), "name" => strtoupper("ARBD 3"), "lokaliti_id" => "3"]);
        Blok::create(["code" => strtoupper("ARBD 5"), "name" => strtoupper("ARBD 5"), "lokaliti_id" => "3"]);
        Blok::create(["code" => strtoupper("ARBD 5A4"), "name" => strtoupper("ARBD 5A4"), "lokaliti_id" => "3"]);
        Blok::create(["code" => strtoupper("ARBD 4"), "name" => strtoupper("ARBD 4"), "lokaliti_id" => "3"]);
        Blok::create(["code" => strtoupper("ALBD 5"), "name" => strtoupper("ALBD 5"), "lokaliti_id" => "4"]);
        Blok::create(["code" => strtoupper("ALBD 6"), "name" => strtoupper("ALBD 6"), "lokaliti_id" => "4"]);
        Blok::create(["code" => strtoupper("ARBD 4"), "name" => strtoupper("ARBD 4"), "lokaliti_id" => "4"]);
        Blok::create(["code" => strtoupper("ARBD 3"), "name" => strtoupper("ARBD 3"), "lokaliti_id" => "4"]);
        Blok::create(["code" => strtoupper("ALBD 3"), "name" => strtoupper("ALBD 3"), "lokaliti_id" => "4"]);
        Blok::create(["code" => strtoupper("ALBD 4"), "name" => strtoupper("ALBD 4"), "lokaliti_id" => "4"]);
        Blok::create(["code" => strtoupper("ALBD 9A"), "name" => strtoupper("ALBD 9A"), "lokaliti_id" => "5"]);
        Blok::create(["code" => strtoupper("ARBD 7"), "name" => strtoupper("ARBD 7"), "lokaliti_id" => "5"]);
        Blok::create(["code" => strtoupper("ALBD 9B(9B1)"), "name" => strtoupper("ALBD 9B(9B1)"), "lokaliti_id" => "5"]);
        Blok::create(["code" => strtoupper("ALBD  9(9A-9B)"), "name" => strtoupper("ALBD  9(9A-9B)"), "lokaliti_id" => "5"]);
        Blok::create(["code" => strtoupper("ALBD 7 & ALBD 8"), "name" => strtoupper("ALBD 7 & ALBD 8"), "lokaliti_id" => "5"]);
        Blok::create(["code" => strtoupper("ALBD 7"), "name" => strtoupper("ALBD 7"), "lokaliti_id" => "5"]);
        Blok::create(["code" => strtoupper("ALBD 9"), "name" => strtoupper("ALBD 9"), "lokaliti_id" => "5"]);
        Blok::create(["code" => strtoupper("ALBD 8"), "name" => strtoupper("ALBD 8"), "lokaliti_id" => "5"]);
        Blok::create(["code" => strtoupper("ALBD 9B"), "name" => strtoupper("ALBD 9B"), "lokaliti_id" => "5"]);
        Blok::create(["code" => strtoupper("LBRBD 3"), "name" => strtoupper("LBRBD 3"), "lokaliti_id" => "6"]);
        Blok::create(["code" => strtoupper("LBRBD 2"), "name" => strtoupper("LBRBD 2"), "lokaliti_id" => "6"]);
        Blok::create(["code" => strtoupper("LBRBD 4"), "name" => strtoupper("LBRBD 4"), "lokaliti_id" => "6"]);
        Blok::create(["code" => strtoupper("ALBD 3"), "name" => strtoupper("ALBD 3"), "lokaliti_id" => "6"]);
        Blok::create(["code" => strtoupper("LBRBD 1A"), "name" => strtoupper("LBRBD 1A"), "lokaliti_id" => "6"]);
        Blok::create(["code" => strtoupper("LBRBD 1"), "name" => strtoupper("LBRBD 1"), "lokaliti_id" => "6"]);
        Blok::create(["code" => strtoupper("ABRBD 1A"), "name" => strtoupper("ABRBD 1A"), "lokaliti_id" => "6"]);
        Blok::create(["code" => strtoupper("ALBD 5"), "name" => strtoupper("ALBD 5"), "lokaliti_id" => "6"]);
        Blok::create(["code" => strtoupper("ALBD12"), "name" => strtoupper("ALBD12"), "lokaliti_id" => "6"]);
        Blok::create(["code" => strtoupper("LBLBD 7"), "name" => strtoupper("LBLBD 7"), "lokaliti_id" => "7"]);
        Blok::create(["code" => strtoupper("ALBD 5"), "name" => strtoupper("ALBD 5"), "lokaliti_id" => "7"]);
        Blok::create(["code" => strtoupper("LBRBD 6"), "name" => strtoupper("LBRBD 6"), "lokaliti_id" => "7"]);
        Blok::create(["code" => strtoupper("LBRBD 5"), "name" => strtoupper("LBRBD 5"), "lokaliti_id" => "7"]);
        Blok::create(["code" => strtoupper("LBLBD 6"), "name" => strtoupper("LBLBD 6"), "lokaliti_id" => "7"]);
        Blok::create(["code" => strtoupper("ALBD 6"), "name" => strtoupper("ALBD 6"), "lokaliti_id" => "7"]);
        Blok::create(["code" => strtoupper("LBRBD 7"), "name" => strtoupper("LBRBD 7"), "lokaliti_id" => "7"]);
        Blok::create(["code" => strtoupper("LBLBD 5"), "name" => strtoupper("LBLBD 5"), "lokaliti_id" => "7"]);
        Blok::create(["code" => strtoupper("LBRBD 11"), "name" => strtoupper("LBRBD 11"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("ALBD 8"), "name" => strtoupper("ALBD 8"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("LBRBD 10"), "name" => strtoupper("LBRBD 10"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("LBRBD 12"), "name" => strtoupper("LBRBD 12"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("ALBD 7"), "name" => strtoupper("ALBD 7"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("LBRBD 10\\\/9"), "name" => strtoupper("LBRBD 10\\\/9"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("LBRBD 9"), "name" => strtoupper("LBRBD 9"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("LBLBD 11"), "name" => strtoupper("LBLBD 11"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("LBRBD 8"), "name" => strtoupper("LBRBD 8"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("LBLBD 12"), "name" => strtoupper("LBLBD 12"), "lokaliti_id" => "8"]);
        Blok::create(["code" => strtoupper("LBLBD 1,1A"), "name" => strtoupper("LBLBD 1,1A"), "lokaliti_id" => "9"]);
        Blok::create(["code" => strtoupper("ACRBD 5"), "name" => strtoupper("ACRBD 5"), "lokaliti_id" => "9"]);
        Blok::create(["code" => strtoupper("MAIN CANAL"), "name" => strtoupper("MAIN CANAL"), "lokaliti_id" => "9"]);
        Blok::create(["code" => strtoupper("ACRBD 5,4"), "name" => strtoupper("ACRBD 5,4"), "lokaliti_id" => "9"]);
        Blok::create(["code" => strtoupper("NCD 2B"), "name" => strtoupper("NCD 2B"), "lokaliti_id" => "9"]);
        Blok::create(["code" => strtoupper("LBLBD 4"), "name" => strtoupper("LBLBD 4"), "lokaliti_id" => "9"]);
        Blok::create(["code" => strtoupper("NCD 2B,ACRBD 3,4"), "name" => strtoupper("NCD 2B,ACRBD 3,4"), "lokaliti_id" => "9"]);
        Blok::create(["code" => strtoupper("LBLBD 3"), "name" => strtoupper("LBLBD 3"), "lokaliti_id" => "9"]);
        Blok::create(["code" => strtoupper("LBLBD 1A"), "name" => strtoupper("LBLBD 1A"), "lokaliti_id" => "9"]);
        Blok::create(["code" => strtoupper("ACRBD 7"), "name" => strtoupper("ACRBD 7"), "lokaliti_id" => "10"]);
        Blok::create(["code" => strtoupper("ACLBD 9,9A"), "name" => strtoupper("ACLBD 9,9A"), "lokaliti_id" => "10"]);
        Blok::create(["code" => strtoupper("ACLBD 7"), "name" => strtoupper("ACLBD 7"), "lokaliti_id" => "10"]);
        Blok::create(["code" => strtoupper("ACLBD 8"), "name" => strtoupper("ACLBD 8"), "lokaliti_id" => "10"]);
        Blok::create(["code" => strtoupper("ACRBD 6"), "name" => strtoupper("ACRBD 6"), "lokaliti_id" => "10"]);
        Blok::create(["code" => strtoupper("ACRBD 8"), "name" => strtoupper("ACRBD 8"), "lokaliti_id" => "10"]);
        Blok::create(["code" => strtoupper("ACLBD 9,9A"), "name" => strtoupper("ACLBD 9,9A"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACLBD 9D,9E"), "name" => strtoupper("ACLBD 9D,9E"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACLBD 9D"), "name" => strtoupper("ACLBD 9D"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACLBD 9B"), "name" => strtoupper("ACLBD 9B"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACRBD 8D"), "name" => strtoupper("ACRBD 8D"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("AC 1"), "name" => strtoupper("AC 1"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACRBD 8B\\\/ACLBD (A"), "name" => strtoupper("ACRBD 8B\\\/ACLBD (A"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACRBD 8A"), "name" => strtoupper("ACRBD 8A"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACLBD 8B"), "name" => strtoupper("ACLBD 8B"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACLBD 9"), "name" => strtoupper("ACLBD 9"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACLBD 9C"), "name" => strtoupper("ACLBD 9C"), "lokaliti_id" => "11"]);
        Blok::create(["code" => strtoupper("ACRBD 2"), "name" => strtoupper("ACRBD 2"), "lokaliti_id" => "12"]);
        Blok::create(["code" => strtoupper("ACLBD 3"), "name" => strtoupper("ACLBD 3"), "lokaliti_id" => "12"]);
        Blok::create(["code" => strtoupper("ACLBD 1&2"), "name" => strtoupper("ACLBD 1&2"), "lokaliti_id" => "12"]);
        Blok::create(["code" => strtoupper("ACRBD 1"), "name" => strtoupper("ACRBD 1"), "lokaliti_id" => "12"]);
        Blok::create(["code" => strtoupper("NCD 2,2A"), "name" => strtoupper("NCD 2,2A"), "lokaliti_id" => "12"]);
        Blok::create(["code" => strtoupper("ACRBD 1\\\/NCD 2"), "name" => strtoupper("ACRBD 1\\\/NCD 2"), "lokaliti_id" => "12"]);
        Blok::create(["code" => strtoupper("ACLBD 2"), "name" => strtoupper("ACLBD 2"), "lokaliti_id" => "12"]);
        Blok::create(["code" => strtoupper("NDD 2,2A"), "name" => strtoupper("NDD 2,2A"), "lokaliti_id" => "12"]);
        Blok::create(["code" => strtoupper("FC KEMUNTING"), "name" => strtoupper("FC KEMUNTING"), "lokaliti_id" => "12"]);
        Blok::create(["code" => strtoupper("NCD 1,1A"), "name" => strtoupper("NCD 1,1A"), "lokaliti_id" => "13"]);
        Blok::create(["code" => strtoupper("ACRBD 4"), "name" => strtoupper("ACRBD 4"), "lokaliti_id" => "13"]);
        Blok::create(["code" => strtoupper("ACLBD 6"), "name" => strtoupper("ACLBD 6"), "lokaliti_id" => "13"]);
        Blok::create(["code" => strtoupper("ACLBD 4 UPPER"), "name" => strtoupper("ACLBD 4 UPPER"), "lokaliti_id" => "13"]);
        Blok::create(["code" => strtoupper("ACLBD 5"), "name" => strtoupper("ACLBD 5"), "lokaliti_id" => "13"]);
        Blok::create(["code" => strtoupper("NCD 1"), "name" => strtoupper("NCD 1"), "lokaliti_id" => "13"]);
        Blok::create(["code" => strtoupper("BLOK 5"), "name" => strtoupper("BLOK 5"), "lokaliti_id" => "13"]);
        Blok::create(["code" => strtoupper("ACLBD 4(L)"), "name" => strtoupper("ACLBD 4(L)"), "lokaliti_id" => "14"]);
        Blok::create(["code" => strtoupper("ACLBD 8A"), "name" => strtoupper("ACLBD 8A"), "lokaliti_id" => "14"]);
        Blok::create(["code" => strtoupper("ACLBD 4E,4F"), "name" => strtoupper("ACLBD 4E,4F"), "lokaliti_id" => "14"]);
        Blok::create(["code" => strtoupper("ACLBD 4D"), "name" => strtoupper("ACLBD 4D"), "lokaliti_id" => "14"]);
        Blok::create(["code" => strtoupper("ACLBD 4F"), "name" => strtoupper("ACLBD 4F"), "lokaliti_id" => "14"]);
        Blok::create(["code" => strtoupper("ACLBD 4 E"), "name" => strtoupper("ACLBD 4E"), "lokaliti_id" => "14"]);
        Blok::create(["code" => strtoupper("ACLBD 7A,7B"), "name" => strtoupper("ACLBD 7A,7B"), "lokaliti_id" => "14"]);
        Blok::create(["code" => strtoupper("ALOR SENJAYA (PN 16)"), "name" => strtoupper("ALOR SENJAYA (PN 16)"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 1B,1E"), "name" => strtoupper("CCRBD 1B,1E"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 1-2(PN 2)"), "name" => strtoupper("CCRBD 1-2(PN 2)"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD (U)"), "name" => strtoupper("CCRBD (U)"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 2, DIRECT TAPPING (A3)"), "name" => strtoupper("CCRBD 2, DIRECT TAPPING (A3)"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("LENGKUAS"), "name" => strtoupper("LENGKUAS"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 1D"), "name" => strtoupper("CCRBD 1D"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 1F"), "name" => strtoupper("CCRBD 1F"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 1F"), "name" => strtoupper("CCRBD 1F"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 1F"), "name" => strtoupper("CCRBD 1F"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 1L"), "name" => strtoupper("CCRBD 1L"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 1C"), "name" => strtoupper("CCRBD 1C"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("( MUDA 2 )"), "name" => strtoupper("( MUDA 2 )"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 1L"), "name" => strtoupper("CCRBD 1L"), "lokaliti_id" => "15"]);
        Blok::create(["code" => strtoupper("CCRBD 3E1,3E2"), "name" => strtoupper("CCRBD 3E1,3E2"), "lokaliti_id" => "16"]);
        Blok::create(["code" => strtoupper("CCRBD 3A,3A1"), "name" => strtoupper("CCRBD 3A,3A1"), "lokaliti_id" => "16"]);
        Blok::create(["code" => strtoupper("CCRBD 3"), "name" => strtoupper("CCRBD 3"), "lokaliti_id" => "16"]);
        Blok::create(["code" => strtoupper("CCRBD 3D"), "name" => strtoupper("CCRBD 3D"), "lokaliti_id" => "16"]);
        Blok::create(["code" => strtoupper("CCRBD 1D"), "name" => strtoupper("CCRBD 1D"), "lokaliti_id" => "16"]);
        Blok::create(["code" => strtoupper("CCRBD 2-1"), "name" => strtoupper("CCRBD 2-1"), "lokaliti_id" => "16"]);
        Blok::create(["code" => strtoupper("CCRBD 4,4B"), "name" => strtoupper("CCRBD 4,4B"), "lokaliti_id" => "16"]);
        Blok::create(["code" => strtoupper("CCRBD 3B,3C"), "name" => strtoupper("CCRBD 3B,3C"), "lokaliti_id" => "16"]);
        Blok::create(["code" => strtoupper("CCRBD 10E"), "name" => strtoupper("CCRBD 10E"), "lokaliti_id" => "17"]);
        Blok::create(["code" => strtoupper("CCRBD 10"), "name" => strtoupper("CCRBD 10"), "lokaliti_id" => "17"]);
        Blok::create(["code" => strtoupper("CCRBD 10B"), "name" => strtoupper("CCRBD 10B"), "lokaliti_id" => "17"]);
        Blok::create(["code" => strtoupper("CCRBD 10C"), "name" => strtoupper("CCRBD 10C"), "lokaliti_id" => "17"]);
        Blok::create(["code" => strtoupper("CCRBD 10F"), "name" => strtoupper("CCRBD 10F"), "lokaliti_id" => "17"]);
        Blok::create(["code" => strtoupper("CCRBD 10A"), "name" => strtoupper("CCRBD 10A"), "lokaliti_id" => "17"]);
        Blok::create(["code" => strtoupper("CCRBD 10C2A1"), "name" => strtoupper("CCRBD 10C2A1"), "lokaliti_id" => "17"]);
        Blok::create(["code" => strtoupper("CCRBD 10D"), "name" => strtoupper("CCRBD 10D"), "lokaliti_id" => "17"]);
        Blok::create(["code" => strtoupper("CCRBD 10C2A"), "name" => strtoupper("CCRBD 10C2A"), "lokaliti_id" => "17"]);
        Blok::create(["code" => strtoupper("CCRBD 9B"), "name" => strtoupper("CCRBD 9B"), "lokaliti_id" => "18"]);
        Blok::create(["code" => strtoupper("CCRBD 5,5A"), "name" => strtoupper("CCRBD 5,5A"), "lokaliti_id" => "18"]);
        Blok::create(["code" => strtoupper("CCRBD 9"), "name" => strtoupper("CCRBD 9"), "lokaliti_id" => "18"]);
        Blok::create(["code" => strtoupper("CCRBD 6"), "name" => strtoupper("CCRBD 6"), "lokaliti_id" => "18"]);
        Blok::create(["code" => strtoupper("CCRBD 7"), "name" => strtoupper("CCRBD 7"), "lokaliti_id" => "18"]);
        Blok::create(["code" => strtoupper("CCRBD 8"), "name" => strtoupper("CCRBD 8"), "lokaliti_id" => "18"]);
        Blok::create(["code" => strtoupper("CCRBD 4B"), "name" => strtoupper("CCRBD 4B"), "lokaliti_id" => "18"]);
        Blok::create(["code" => strtoupper("CCRBD 5"), "name" => strtoupper("CCRBD 5"), "lokaliti_id" => "18"]);
        Blok::create(["code" => strtoupper("CCLBD 1"), "name" => strtoupper("CCLBD 1"), "lokaliti_id" => "19"]);
        Blok::create(["code" => strtoupper("CCLBD 2"), "name" => strtoupper("CCLBD 2"), "lokaliti_id" => "19"]);
        Blok::create(["code" => strtoupper("CCRBD 2A2, 2A3"), "name" => strtoupper("CCRBD 2A2, 2A3"), "lokaliti_id" => "19"]);
        Blok::create(["code" => strtoupper("CCLBD 2A4"), "name" => strtoupper("CCLBD 2A4"), "lokaliti_id" => "19"]);
        Blok::create(["code" => strtoupper("CCLBD 1B"), "name" => strtoupper("CCLBD 1B"), "lokaliti_id" => "19"]);
        Blok::create(["code" => strtoupper("CCLBD 2AL"), "name" => strtoupper("CCLBD 2AL"), "lokaliti_id" => "19"]);
        Blok::create(["code" => strtoupper("SCRBD 1"), "name" => strtoupper("SCRBD 1"), "lokaliti_id" => "20"]);
        Blok::create(["code" => strtoupper("SCRBD 1-3"), "name" => strtoupper("SCRBD 1-3"), "lokaliti_id" => "20"]);
        Blok::create(["code" => strtoupper("SCRBD 1-2"), "name" => strtoupper("SCRBD 1-2"), "lokaliti_id" => "20"]);
        Blok::create(["code" => strtoupper("SCRBD 1-1"), "name" => strtoupper("SCRBD 1-1"), "lokaliti_id" => "20"]);
        Blok::create(["code" => strtoupper("CCLBD 9"), "name" => strtoupper("CCLBD 9"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCLBD 8"), "name" => strtoupper("CCLBD 8"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCD 1C,CCLBD 10"), "name" => strtoupper("CCD 1C,CCLBD 10"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCRBD 14,14A"), "name" => strtoupper("CCRBD 14,14A"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCRBD 14B"), "name" => strtoupper("CCRBD 14B"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCLBD 7E,7F"), "name" => strtoupper("CCLBD 7E,7F"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCLBD 7C"), "name" => strtoupper("CCLBD 7C"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCLBD 10"), "name" => strtoupper("CCLBD 10"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCRBD14C"), "name" => strtoupper("CCRBD14C"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCLBD 7D"), "name" => strtoupper("CCLBD 7D"), "lokaliti_id" => "21"]);
        Blok::create(["code" => strtoupper("CCRBD 11"), "name" => strtoupper("CCRBD 11"), "lokaliti_id" => "22"]);
        Blok::create(["code" => strtoupper("CCD 1A"), "name" => strtoupper("CCD 1A"), "lokaliti_id" => "22"]);
        Blok::create(["code" => strtoupper("CCRBD 12"), "name" => strtoupper("CCRBD 12"), "lokaliti_id" => "22"]);
        Blok::create(["code" => strtoupper("CCRBD 13"), "name" => strtoupper("CCRBD 13"), "lokaliti_id" => "22"]);
        Blok::create(["code" => strtoupper("CCD 1A\\\/DR 8"), "name" => strtoupper("CCD 1A\\\/DR 8"), "lokaliti_id" => "22"]);
        Blok::create(["code" => strtoupper("CCLBD 6"), "name" => strtoupper("CCLBD 6"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("CCLBD 4"), "name" => strtoupper("CCLBD 4"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("CCLBD 7E,7F"), "name" => strtoupper("CCLBD 7E,7F"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("CCLBD 6C"), "name" => strtoupper("CCLBD 6C"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("CCRBD 4"), "name" => strtoupper("CCRBD 4"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("CCLBD 6B"), "name" => strtoupper("CCLBD 6B"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("CCLBD 6A & 6"), "name" => strtoupper("CCLBD 6A & 6"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("CCLBD 6C &6D"), "name" => strtoupper("CCLBD 6C &6D"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("CCLBD 6A & 6C"), "name" => strtoupper("CCLBD 6A & 6C"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("CCLBD 3 & 4"), "name" => strtoupper("CCLBD 3 & 4"), "lokaliti_id" => "23"]);
        Blok::create(["code" => strtoupper("SCRBD 5B"), "name" => strtoupper("SCRBD 5B"), "lokaliti_id" => "24"]);
        Blok::create(["code" => strtoupper("SCRBD 5B1"), "name" => strtoupper("SCRBD 5B1"), "lokaliti_id" => "24"]);
        Blok::create(["code" => strtoupper("SCRBD 5B2,B3"), "name" => strtoupper("SCRBD 5B2,B3"), "lokaliti_id" => "24"]);
        Blok::create(["code" => strtoupper("SCRBD 5A"), "name" => strtoupper("SCRBD 5A"), "lokaliti_id" => "24"]);
        Blok::create(["code" => strtoupper("SCRBD 5B2"), "name" => strtoupper("SCRBD 5B2"), "lokaliti_id" => "24"]);
        Blok::create(["code" => strtoupper("SCRBD 3"), "name" => strtoupper("SCRBD 3"), "lokaliti_id" => "25"]);
        Blok::create(["code" => strtoupper("SCRBD 4"), "name" => strtoupper("SCRBD 4"), "lokaliti_id" => "25"]);
        Blok::create(["code" => strtoupper("SCRBD 2"), "name" => strtoupper("SCRBD 2"), "lokaliti_id" => "25"]);
        Blok::create(["code" => strtoupper("SCLBD 2"), "name" => strtoupper("SCLBD 2"), "lokaliti_id" => "25"]);
        Blok::create(["code" => strtoupper("SCRBD 7B"), "name" => strtoupper("SCRBD 7B"), "lokaliti_id" => "26"]);
        Blok::create(["code" => strtoupper("SCRBD 7C"), "name" => strtoupper("SCRBD 7C"), "lokaliti_id" => "26"]);
        Blok::create(["code" => strtoupper("SCRBD  5 UPPER"), "name" => strtoupper("SCRBD  5 UPPER"), "lokaliti_id" => "26"]);
        Blok::create(["code" => strtoupper("SCRBD 7A"), "name" => strtoupper("SCRBD 7A"), "lokaliti_id" => "26"]);
        Blok::create(["code" => strtoupper("SCRBD  5A"), "name" => strtoupper("SCRBD  5A"), "lokaliti_id" => "26"]);
        Blok::create(["code" => strtoupper("SCRBD 6"), "name" => strtoupper("SCRBD 6"), "lokaliti_id" => "26"]);
        Blok::create(["code" => strtoupper("SCRBD  5B"), "name" => strtoupper("SCRBD  5B"), "lokaliti_id" => "26"]);
        Blok::create(["code" => strtoupper("SCLBD 3"), "name" => strtoupper("SCLBD 3"), "lokaliti_id" => "27"]);
        Blok::create(["code" => strtoupper("SCD 1A"), "name" => strtoupper("SCD 1A"), "lokaliti_id" => "27"]);
        Blok::create(["code" => strtoupper("SCRBD 6"), "name" => strtoupper("SCRBD 6"), "lokaliti_id" => "27"]);
        Blok::create(["code" => strtoupper("SCRBD 7A"), "name" => strtoupper("SCRBD 7A"), "lokaliti_id" => "27"]);
        Blok::create(["code" => strtoupper("SCD 1"), "name" => strtoupper("SCD 1"), "lokaliti_id" => "27"]);
        Blok::create(["code" => strtoupper("SCD 1 & 1A"), "name" => strtoupper("SCD 1 & 1A"), "lokaliti_id" => "27"]);
        Blok::create(["code" => strtoupper("SCD 1 & SCLBD 3"), "name" => strtoupper("SCD 1 & SCLBD 3"), "lokaliti_id" => "27"]);
        Blok::create(["code" => strtoupper("SCRBD 5"), "name" => strtoupper("SCRBD 5"), "lokaliti_id" => "27"]);
    }
}
