<?php

use Illuminate\Database\Seeder;
use App\Blok;

class BlokTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Blok::create(['code' => 'ALBD 1','name' => 'ALBD 1','lokaliti_id' => '1']);
        Blok::create(['code' => 'ALBD 2','name' => 'ALBD 2','lokaliti_id' => '1']);
        Blok::create(['code' => 'ALBD 1 & ALBD 2','name' => 'ALBD 1 & ALBD 2','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 2','name' => 'ARBD 2','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 1(1d,1g,1f)','name' => 'ARBD 1(1d,1g,1f)','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 1(1d,1g,1f)','name' => 'ARBD 1(1d,1g,1f)','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 1(1d,1g,1f)','name' => 'ARBD 1(1d,1g,1f)','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 2','name' => 'ARBD 2','lokaliti_id' => '1']);
        Blok::create(['code' => 'NCD 5a1','name' => 'NCD 5a1','lokaliti_id' => '1']);
        Blok::create(['code' => 'ALBD 1','name' => 'ALBD 1','lokaliti_id' => '1']);
        Blok::create(['code' => 'NCD 3a','name' => 'NCD 3a','lokaliti_id' => '1']);
        Blok::create(['code' => 'NCD 3a','name' => 'NCD 3a','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 1 1f','name' => 'ARBD 1 1f','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 2','name' => 'ARBD 2','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 2','name' => 'ARBD 2','lokaliti_id' => '1']);
        Blok::create(['code' => 'ALBD 2','name' => 'ALBD 2','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 2','name' => 'ARBD 2','lokaliti_id' => '1']);
        Blok::create(['code' => 'ARBD 6','name' => 'ARBD 6','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7a(a1,a2,a3,a4','name' => 'ARBD 7a(a1,a2,a3,a4','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 6','name' => 'ARBD 6','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 6','name' => 'ARBD 6','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7 (b,c,d,e)','name' => 'ARBD 7 (b,c,d,e)','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7a (a1,a2,a3,a4)','name' => 'ARBD 7a (a1,a2,a3,a4)','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7','name' => 'ARBD 7','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7 (b,c,d,e)','name' => 'ARBD 7 (b,c,d,e)','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7 (b,c,d,e)','name' => 'ARBD 7 (b,c,d,e)','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7b','name' => 'ARBD 7b','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 5','name' => 'ARBD 5','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 5a5','name' => 'ARBD 5a5','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7','name' => 'ARBD 7','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7','name' => 'ARBD 7','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 5a','name' => 'ARBD 5a','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 6','name' => 'ARBD 6','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 5','name' => 'ARBD 5','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7a3','name' => 'ARBD 7a3','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7a','name' => 'ARBD 7a','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 5','name' => 'ARBD 5','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 5','name' => 'ARBD 5','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 5a','name' => 'ARBD 5a','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 5a','name' => 'ARBD 5a','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 7a','name' => 'ARBD 7a','lokaliti_id' => '2']);
        Blok::create(['code' => 'ARBD 5a2','name' => 'ARBD 5a2','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 5a2','name' => 'ARBD 5a2','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 5a2','name' => 'ARBD 5a2','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 5a','name' => 'ARBD 5a','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 1c','name' => 'ARBD 1c','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 1(1d,1g,2f)','name' => 'ARBD 1(1d,1g,2f)','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 1(1d,1g,2f)','name' => 'ARBD 1(1d,1g,2f)','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 1C','name' => 'ARBD 1C','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 3','name' => 'ARBD 3','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 5','name' => 'ARBD 5','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 5a4','name' => 'ARBD 5a4','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 4','name' => 'ARBD 4','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 5','name' => 'ARBD 5','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 5a4','name' => 'ARBD 5a4','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 5a','name' => 'ARBD 5a','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 1c','name' => 'ARBD 1c','lokaliti_id' => '3']);
        Blok::create(['code' => 'ARBD 1c','name' => 'ARBD 1c','lokaliti_id' => '3']);
        Blok::create(['code' => 'ALBD 5','name' => 'ALBD 5','lokaliti_id' => '4']);
        Blok::create(['code' => 'ALBD 6','name' => 'ALBD 6','lokaliti_id' => '4']);
        Blok::create(['code' => 'ARBD 4','name' => 'ARBD 4','lokaliti_id' => '4']);
        Blok::create(['code' => 'ARBD 4','name' => 'ARBD 4','lokaliti_id' => '4']);
        Blok::create(['code' => 'ARBD 3','name' => 'ARBD 3','lokaliti_id' => '4']);
        Blok::create(['code' => 'ARBD 3','name' => 'ARBD 3','lokaliti_id' => '4']);
        Blok::create(['code' => 'ALBD 3','name' => 'ALBD 3','lokaliti_id' => '4']);
        Blok::create(['code' => 'ALBD 4','name' => 'ALBD 4','lokaliti_id' => '4']);
        Blok::create(['code' => 'ALBD 4','name' => 'ALBD 4','lokaliti_id' => '4']);
        Blok::create(['code' => 'ALBD 6','name' => 'ALBD 6','lokaliti_id' => '4']);
        Blok::create(['code' => 'ALBD 6','name' => 'ALBD 6','lokaliti_id' => '4']);
        Blok::create(['code' => 'ALBD 9a','name' => 'ALBD 9a','lokaliti_id' => '5']);
        Blok::create(['code' => 'ARBD 7','name' => 'ARBD 7','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9b(9b1)','name' => 'ALBD 9b(9b1)','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD  9(9a-9b)','name' => 'ALBD  9(9a-9b)','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 7 & ALBD 8','name' => 'ALBD 7 & ALBD 8','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 7','name' => 'ALBD 7','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9','name' => 'ALBD 9','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9','name' => 'ALBD 9','lokaliti_id' => '5']);
        Blok::create(['code' => 'ARBD 6','name' => 'ARBD 6','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 8','name' => 'ALBD 8','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9','name' => 'ALBD 9','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9','name' => 'ALBD 9','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9','name' => 'ALBD 9','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9a','name' => 'ALBD 9a','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 8','name' => 'ALBD 8','lokaliti_id' => '5']);
        Blok::create(['code' => 'ARBD 6','name' => 'ARBD 6','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9b(9b1)','name' => 'ALBD 9b(9b1)','lokaliti_id' => '5']);
        Blok::create(['code' => 'ARBD 6','name' => 'ARBD 6','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9','name' => 'ALBD 9','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 9b','name' => 'ALBD 9b','lokaliti_id' => '5']);
        Blok::create(['code' => 'ALBD 7','name' => 'ALBD 7','lokaliti_id' => '5']);
        Blok::create(['code' => 'LBRBD 3','name' => 'LBRBD 3','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBRBD 3','name' => 'LBRBD 3','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBRBD 2','name' => 'LBRBD 2','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBRBD 4','name' => 'LBRBD 4','lokaliti_id' => '6']);
        Blok::create(['code' => 'ALBD 3','name' => 'ALBD 3','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBRBD 1a','name' => 'LBRBD 1a','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBRBD 1','name' => 'LBRBD 1','lokaliti_id' => '6']);
        Blok::create(['code' => 'ABRBD 1A','name' => 'ABRBD 1A','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBRBD 1a','name' => 'LBRBD 1a','lokaliti_id' => '6']);
        Blok::create(['code' => 'ALBD 5','name' => 'ALBD 5','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBRBD 1a','name' => 'LBRBD 1a','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBRBD 1a','name' => 'LBRBD 1a','lokaliti_id' => '6']);
        Blok::create(['code' => 'ALBD12','name' => 'ALBD12','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBRBD 4','name' => 'LBRBD 4','lokaliti_id' => '6']);
        Blok::create(['code' => 'LBLBD 7','name' => 'LBLBD 7','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBLBD 7','name' => 'LBLBD 7','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBLBD 7','name' => 'LBLBD 7','lokaliti_id' => '7']);
        Blok::create(['code' => 'ALBD 5','name' => 'ALBD 5','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBRBD 6','name' => 'LBRBD 6','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBRBD 5','name' => 'LBRBD 5','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBLBD 6','name' => 'LBLBD 6','lokaliti_id' => '7']);
        Blok::create(['code' => 'ALBD 6','name' => 'ALBD 6','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBLBD 6','name' => 'LBLBD 6','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBRBD 6','name' => 'LBRBD 6','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBRBD 6','name' => 'LBRBD 6','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBRBD 6','name' => 'LBRBD 6','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBRBD 6','name' => 'LBRBD 6','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBRBD 7','name' => 'LBRBD 7','lokaliti_id' => '7']);
        Blok::create(['code' => 'ALBD 5','name' => 'ALBD 5','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBLBD 5','name' => 'LBLBD 5','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBRBD 6','name' => 'LBRBD 6','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBLBD 5','name' => 'LBLBD 5','lokaliti_id' => '7']);
        Blok::create(['code' => 'ALBD 5','name' => 'ALBD 5','lokaliti_id' => '7']);
        Blok::create(['code' => 'LBRBD 11','name' => 'LBRBD 11','lokaliti_id' => '8']);
        Blok::create(['code' => 'ALBD 8','name' => 'ALBD 8','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 10','name' => 'LBRBD 10','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBLBD 11','name' => 'LBLBD 11','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBLBD 11','name' => 'LBLBD 11','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 12','name' => 'LBRBD 12','lokaliti_id' => '8']);
        Blok::create(['code' => 'ALBD 7','name' => 'ALBD 7','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 10\/9','name' => 'LBRBD 10\/9','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 10','name' => 'LBRBD 10','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 11','name' => 'LBRBD 11','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 9','name' => 'LBRBD 9','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBLBD 11','name' => 'LBLBD 11','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 8','name' => 'LBRBD 8','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 9','name' => 'LBRBD 9','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 10','name' => 'LBRBD 10','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 9','name' => 'LBRBD 9','lokaliti_id' => '8']);
        Blok::create(['code' => 'ALBD 9','name' => 'ALBD 9','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBRBD 10','name' => 'LBRBD 10','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBLBD 12','name' => 'LBLBD 12','lokaliti_id' => '8']);
        Blok::create(['code' => 'LBLBD 1,1a','name' => 'LBLBD 1,1a','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 1,1a','name' => 'LBLBD 1,1a','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 1,1a','name' => 'LBLBD 1,1a','lokaliti_id' => '9']);
        Blok::create(['code' => 'ACRBD 5','name' => 'ACRBD 5','lokaliti_id' => '9']);
        Blok::create(['code' => 'Main Canal','name' => 'Main Canal','lokaliti_id' => '9']);
        Blok::create(['code' => 'Main Canal','name' => 'Main Canal','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 1,1a','name' => 'LBLBD 1,1a','lokaliti_id' => '9']);
        Blok::create(['code' => 'ACRBD 5,4','name' => 'ACRBD 5,4','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 1,1a','name' => 'LBLBD 1,1a','lokaliti_id' => '9']);
        Blok::create(['code' => 'NCD 2B','name' => 'NCD 2B','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 4','name' => 'LBLBD 4','lokaliti_id' => '9']);
        Blok::create(['code' => 'NCD 2b,ACRBD 3,4','name' => 'NCD 2b,ACRBD 3,4','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 4','name' => 'LBLBD 4','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 3','name' => 'LBLBD 3','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 1,1a','name' => 'LBLBD 1,1a','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 1a','name' => 'LBLBD 1a','lokaliti_id' => '9']);
        Blok::create(['code' => '','name' => '','lokaliti_id' => '9']);
        Blok::create(['code' => 'LBLBD 4','name' => 'LBLBD 4','lokaliti_id' => '9']);
        Blok::create(['code' => 'NCD 2B','name' => 'NCD 2B','lokaliti_id' => '9']);
        Blok::create(['code' => 'ACRBD 7','name' => 'ACRBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 9,9a','name' => 'ACLBD 9,9a','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACRBD 7','name' => 'ACRBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 7','name' => 'ACLBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 7','name' => 'ACLBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 7','name' => 'ACLBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 7','name' => 'ACLBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACRBD 7','name' => 'ACRBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACRBD 7','name' => 'ACRBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 8','name' => 'ACLBD 8','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 8','name' => 'ACLBD 8','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 8','name' => 'ACLBD 8','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 9,9a','name' => 'ACLBD 9,9a','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACRBD 7','name' => 'ACRBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACRBD 6','name' => 'ACRBD 6','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACRBD 7','name' => 'ACRBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACRBD 8','name' => 'ACRBD 8','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 8','name' => 'ACLBD 8','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 8','name' => 'ACLBD 8','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 8','name' => 'ACLBD 8','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 9,9a','name' => 'ACLBD 9,9a','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACRBD 7','name' => 'ACRBD 7','lokaliti_id' => '10']);
        Blok::create(['code' => '','name' => '','lokaliti_id' => '10']);
        Blok::create(['code' => 'ACLBD 9,9a','name' => 'ACLBD 9,9a','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9,9a','name' => 'ACLBD 9,9a','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9,9a','name' => 'ACLBD 9,9a','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9,9a','name' => 'ACLBD 9,9a','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9d,9e','name' => 'ACLBD 9d,9e','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9d','name' => 'ACLBD 9d','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9b','name' => 'ACLBD 9b','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACRBD 8d','name' => 'ACRBD 8d','lokaliti_id' => '11']);
        Blok::create(['code' => 'AC 1','name' => 'AC 1','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACRBD 8b\/ACLBD (a','name' => 'ACRBD 8b\/ACLBD (a','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9,9a','name' => 'ACLBD 9,9a','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACRBD 8a','name' => 'ACRBD 8a','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 8b','name' => 'ACLBD 8b','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9','name' => 'ACLBD 9','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9','name' => 'ACLBD 9','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACLBD 9c','name' => 'ACLBD 9c','lokaliti_id' => '11']);
        Blok::create(['code' => 'ACRBD 2','name' => 'ACRBD 2','lokaliti_id' => '12']);
        Blok::create(['code' => 'ACLBD 3','name' => 'ACLBD 3','lokaliti_id' => '12']);
        Blok::create(['code' => 'ACLBD 1&2','name' => 'ACLBD 1&2','lokaliti_id' => '12']);
        Blok::create(['code' => 'ACRBD 1','name' => 'ACRBD 1','lokaliti_id' => '12']);
        Blok::create(['code' => 'ACRBD 2','name' => 'ACRBD 2','lokaliti_id' => '12']);
        Blok::create(['code' => 'NCD 2,2a','name' => 'NCD 2,2a','lokaliti_id' => '12']);
        Blok::create(['code' => 'ACRBD 1\/NCD 2','name' => 'ACRBD 1\/NCD 2','lokaliti_id' => '12']);
        Blok::create(['code' => 'ACRBD 1','name' => 'ACRBD 1','lokaliti_id' => '12']);
        Blok::create(['code' => 'ACLBD 2','name' => 'ACLBD 2','lokaliti_id' => '12']);
        Blok::create(['code' => '','name' => '','lokaliti_id' => '12']);
        Blok::create(['code' => '','name' => '','lokaliti_id' => '12']);
        Blok::create(['code' => 'NDD 2,2a','name' => 'NDD 2,2a','lokaliti_id' => '12']);
        Blok::create(['code' => 'FC Kemunting','name' => 'FC Kemunting','lokaliti_id' => '12']);
        Blok::create(['code' => 'ACLBD 2','name' => 'ACLBD 2','lokaliti_id' => '12']);
        Blok::create(['code' => 'NCD 2 ,2a','name' => 'NCD 2 ,2a','lokaliti_id' => '12']);
        Blok::create(['code' => 'NCD 2 ,2a','name' => 'NCD 2 ,2a','lokaliti_id' => '12']);
        Blok::create(['code' => 'NCD 2 ,2a','name' => 'NCD 2 ,2a','lokaliti_id' => '12']);
        Blok::create(['code' => 'ACLBD 3','name' => 'ACLBD 3','lokaliti_id' => '12']);
        Blok::create(['code' => 'NCD 2 ,2a','name' => 'NCD 2 ,2a','lokaliti_id' => '12']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACRBD 4','name' => 'ACRBD 4','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 6','name' => 'ACLBD 6','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 4 Upper','name' => 'ACLBD 4 Upper','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 4 Upper','name' => 'ACLBD 4 Upper','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 5','name' => 'ACLBD 5','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 5','name' => 'ACLBD 5','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 6','name' => 'ACLBD 6','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 5','name' => 'ACLBD 5','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACRBD 4','name' => 'ACRBD 4','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACRBD 4','name' => 'ACRBD 4','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 5','name' => 'ACLBD 5','lokaliti_id' => '13']);
        Blok::create(['code' => '','name' => '','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 6','name' => 'ACLBD 6','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 5','name' => 'ACLBD 5','lokaliti_id' => '13']);
        Blok::create(['code' => '','name' => '','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 3','name' => 'ACLBD 3','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 3','name' => 'ACLBD 3','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1','name' => 'NCD 1','lokaliti_id' => '13']);
        Blok::create(['code' => 'Blok 5','name' => 'Blok 5','lokaliti_id' => '13']);
        Blok::create(['code' => 'NCD 1,1a','name' => 'NCD 1,1a','lokaliti_id' => '13']);
        Blok::create(['code' => 'ACLBD 4(L)','name' => 'ACLBD 4(L)','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 7','name' => 'ACLBD 7','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 7','name' => 'ACLBD 7','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4 (L)','name' => 'ACLBD 4 (L)','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4 (L)','name' => 'ACLBD 4 (L)','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 7','name' => 'ACLBD 7','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 7','name' => 'ACLBD 7','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 8a','name' => 'ACLBD 8a','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4e,4f','name' => 'ACLBD 4e,4f','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 8a','name' => 'ACLBD 8a','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 8a','name' => 'ACLBD 8a','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4 d','name' => 'ACLBD 4 d','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4f','name' => 'ACLBD 4f','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4 d','name' => 'ACLBD 4 d','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4 e','name' => 'ACLBD 4 e','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 7a,7b','name' => 'ACLBD 7a,7b','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4 d','name' => 'ACLBD 4 d','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 7a,7b','name' => 'ACLBD 7a,7b','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4 d','name' => 'ACLBD 4 d','lokaliti_id' => '14']);
        Blok::create(['code' => 'ACLBD 4f','name' => 'ACLBD 4f','lokaliti_id' => '14']);
        Blok::create(['code' => 'Alor Senjaya (PN 16)','name' => 'Alor Senjaya (PN 16)','lokaliti_id' => '15']);
        Blok::create(['code' => 'Alor Senjaya (PN 16)','name' => 'Alor Senjaya (PN 16)','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1b,1e','name' => 'CCRBD 1b,1e','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1-2(PN 2)','name' => 'CCRBD 1-2(PN 2)','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD (U)','name' => 'CCRBD (U)','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 2, Direct Tapping (A3)','name' => 'CCRBD 2, Direct Tapping (A3)','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 2, Direct Tapping (A3)','name' => 'CCRBD 2, Direct Tapping (A3)','lokaliti_id' => '15']);
        Blok::create(['code' => 'Lengkuas','name' => 'Lengkuas','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1d','name' => 'CCRBD 1d','lokaliti_id' => '15']);
        Blok::create(['code' => 'Alor Senjaya (PN16)','name' => 'Alor Senjaya (PN16)','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1f','name' => 'CCRBD 1f','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1b , 1e','name' => 'CCRBD 1b , 1e','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1b , 1e','name' => 'CCRBD 1b , 1e','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1b , 1e','name' => 'CCRBD 1b , 1e','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1f','name' => 'CCRBD 1f','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1f','name' => 'CCRBD 1f','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1L','name' => 'CCRBD 1L','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1c','name' => 'CCRBD 1c','lokaliti_id' => '15']);
        Blok::create(['code' => '( MUDA 2 )','name' => '( MUDA 2 )','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1L','name' => 'CCRBD 1L','lokaliti_id' => '15']);
        Blok::create(['code' => '','name' => '','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 1b , 1e','name' => 'CCRBD 1b , 1e','lokaliti_id' => '15']);
        Blok::create(['code' => 'CCRBD 3e1,3e2','name' => 'CCRBD 3e1,3e2','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3e1,3e2','name' => 'CCRBD 3e1,3e2','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3e1,3e2','name' => 'CCRBD 3e1,3e2','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3e1,3e2','name' => 'CCRBD 3e1,3e2','lokaliti_id' => '16']);
        Blok::create(['code' => '','name' => '','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3a,3a1','name' => 'CCRBD 3a,3a1','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3a,3a1','name' => 'CCRBD 3a,3a1','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3a,3a1','name' => 'CCRBD 3a,3a1','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3','name' => 'CCRBD 3','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3a,3a1','name' => 'CCRBD 3a,3a1','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3d','name' => 'CCRBD 3d','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 1d','name' => 'CCRBD 1d','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 2-1','name' => 'CCRBD 2-1','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 4,4b','name' => 'CCRBD 4,4b','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3d','name' => 'CCRBD 3d','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3b,3c','name' => 'CCRBD 3b,3c','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3e1,3e2','name' => 'CCRBD 3e1,3e2','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3d','name' => 'CCRBD 3d','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 3d','name' => 'CCRBD 3d','lokaliti_id' => '16']);
        Blok::create(['code' => 'CCRBD 10e','name' => 'CCRBD 10e','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10e','name' => 'CCRBD 10e','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10','name' => 'CCRBD 10','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10','name' => 'CCRBD 10','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10b','name' => 'CCRBD 10b','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10c','name' => 'CCRBD 10c','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10f','name' => 'CCRBD 10f','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10','name' => 'CCRBD 10','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10a','name' => 'CCRBD 10a','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10f','name' => 'CCRBD 10f','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10c2a1','name' => 'CCRBD 10c2a1','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10c2a1','name' => 'CCRBD 10c2a1','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10d','name' => 'CCRBD 10d','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10','name' => 'CCRBD 10','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10c2a','name' => 'CCRBD 10c2a','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 10c2a1','name' => 'CCRBD 10c2a1','lokaliti_id' => '17']);
        Blok::create(['code' => 'CCRBD 9b','name' => 'CCRBD 9b','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 9b','name' => 'CCRBD 9b','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 5,5a','name' => 'CCRBD 5,5a','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 9','name' => 'CCRBD 9','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 5,5a','name' => 'CCRBD 5,5a','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 6','name' => 'CCRBD 6','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 7','name' => 'CCRBD 7','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 8','name' => 'CCRBD 8','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 4b','name' => 'CCRBD 4b','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 6','name' => 'CCRBD 6','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 5','name' => 'CCRBD 5','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 8','name' => 'CCRBD 8','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCRBD 5','name' => 'CCRBD 5','lokaliti_id' => '18']);
        Blok::create(['code' => 'CCLBD 1','name' => 'CCLBD 1','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 1','name' => 'CCLBD 1','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 2','name' => 'CCLBD 2','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCRBD 2a2, 2a3','name' => 'CCRBD 2a2, 2a3','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 1','name' => 'CCLBD 1','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 2a4','name' => 'CCLBD 2a4','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 1b','name' => 'CCLBD 1b','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 2aL','name' => 'CCLBD 2aL','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 2aL','name' => 'CCLBD 2aL','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 1','name' => 'CCLBD 1','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 2','name' => 'CCLBD 2','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 1','name' => 'CCLBD 1','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 2aL','name' => 'CCLBD 2aL','lokaliti_id' => '19']);
        Blok::create(['code' => 'CCLBD 1','name' => 'CCLBD 1','lokaliti_id' => '19']);
        Blok::create(['code' => 'SCRBD 1','name' => 'SCRBD 1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1','name' => 'SCRBD 1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1-3','name' => 'SCRBD 1-3','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1-2','name' => 'SCRBD 1-2','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1-2','name' => 'SCRBD 1-2','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1','name' => 'SCRBD 1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1','name' => 'SCRBD 1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1','name' => 'SCRBD 1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1-2','name' => 'SCRBD 1-2','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1-1','name' => 'SCRBD 1-1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1-1','name' => 'SCRBD 1-1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1','name' => 'SCRBD 1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1-1','name' => 'SCRBD 1-1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1','name' => 'SCRBD 1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1','name' => 'SCRBD 1','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1-2','name' => 'SCRBD 1-2','lokaliti_id' => '20']);
        Blok::create(['code' => 'SCRBD 1-1','name' => 'SCRBD 1-1','lokaliti_id' => '20']);
        Blok::create(['code' => 'CCLBD 9','name' => 'CCLBD 9','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCLBD 8','name' => 'CCLBD 8','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCLBD 8','name' => 'CCLBD 8','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCD 1c,CCLBD 10','name' => 'CCD 1c,CCLBD 10','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCRBD 14,14a','name' => 'CCRBD 14,14a','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCRBD 14b','name' => 'CCRBD 14b','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCLBD 7e,7f','name' => 'CCLBD 7e,7f','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCLBD 7c','name' => 'CCLBD 7c','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCLBD 7e,7f','name' => 'CCLBD 7e,7f','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCD 1c,CCLBD 10','name' => 'CCD 1c,CCLBD 10','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCLBD 10','name' => 'CCLBD 10','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCRBD14c','name' => 'CCRBD14c','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCLBD 7d','name' => 'CCLBD 7d','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCLBD 7c','name' => 'CCLBD 7c','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCD 1c,CCLBD 10','name' => 'CCD 1c,CCLBD 10','lokaliti_id' => '21']);
        Blok::create(['code' => 'CCRBD 11','name' => 'CCRBD 11','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCRBD 11','name' => 'CCRBD 11','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCRBD 11','name' => 'CCRBD 11','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCRBD 11','name' => 'CCRBD 11','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCRBD 11','name' => 'CCRBD 11','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCD 1a','name' => 'CCD 1a','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCRBD 12','name' => 'CCRBD 12','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCRBD 13','name' => 'CCRBD 13','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCD 1a','name' => 'CCD 1a','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCD 1a\/Dr 8','name' => 'CCD 1a\/Dr 8','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCRBD 13','name' => 'CCRBD 13','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCD 1a','name' => 'CCD 1a','lokaliti_id' => '22']);
        Blok::create(['code' => 'CCLBD 6','name' => 'CCLBD 6','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 6','name' => 'CCLBD 6','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 4','name' => 'CCLBD 4','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 4','name' => 'CCLBD 4','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 7e,7f','name' => 'CCLBD 7e,7f','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 6C','name' => 'CCLBD 6C','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCRBD 4','name' => 'CCRBD 4','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 7e,7f','name' => 'CCLBD 7e,7f','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 4','name' => 'CCLBD 4','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 6b','name' => 'CCLBD 6b','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 6','name' => 'CCLBD 6','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 6a & 6','name' => 'CCLBD 6a & 6','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 6c &6d','name' => 'CCLBD 6c &6d','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 6c &6d','name' => 'CCLBD 6c &6d','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 6a & 6c','name' => 'CCLBD 6a & 6c','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 3 & 4','name' => 'CCLBD 3 & 4','lokaliti_id' => '23']);
        Blok::create(['code' => 'CCLBD 6c','name' => 'CCLBD 6c','lokaliti_id' => '23']);
        Blok::create(['code' => 'SCRBD 5b','name' => 'SCRBD 5b','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b','name' => 'SCRBD 5b','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b','name' => 'SCRBD 5b','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b','name' => 'SCRBD 5b','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b1','name' => 'SCRBD 5b1','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b2,b3','name' => 'SCRBD 5b2,b3','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5a','name' => 'SCRBD 5a','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5a','name' => 'SCRBD 5a','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b2','name' => 'SCRBD 5b2','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b','name' => 'SCRBD 5b','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b2','name' => 'SCRBD 5b2','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b','name' => 'SCRBD 5b','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 5b','name' => 'SCRBD 5b','lokaliti_id' => '24']);
        Blok::create(['code' => 'SCRBD 3','name' => 'SCRBD 3','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 3','name' => 'SCRBD 3','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 2','name' => 'SCRBD 2','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 3','name' => 'SCRBD 3','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCLBD 2','name' => 'SCLBD 2','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 2','name' => 'SCRBD 2','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 3','name' => 'SCRBD 3','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 4','name' => 'SCRBD 4','lokaliti_id' => '25']);
        Blok::create(['code' => 'SCRBD 7b','name' => 'SCRBD 7b','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD 7b','name' => 'SCRBD 7b','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD 7c','name' => 'SCRBD 7c','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD 7b','name' => 'SCRBD 7b','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD  5 Upper','name' => 'SCRBD  5 Upper','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD 7a','name' => 'SCRBD 7a','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD 7c','name' => 'SCRBD 7c','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD 7c','name' => 'SCRBD 7c','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD  5a','name' => 'SCRBD  5a','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD 7a','name' => 'SCRBD 7a','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD 6','name' => 'SCRBD 6','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD 7c','name' => 'SCRBD 7c','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD  5a','name' => 'SCRBD  5a','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD  5b','name' => 'SCRBD  5b','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD  5a','name' => 'SCRBD  5a','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD  5 Upper','name' => 'SCRBD  5 Upper','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCRBD  5a','name' => 'SCRBD  5a','lokaliti_id' => '26']);
        Blok::create(['code' => 'SCLBD 3','name' => 'SCLBD 3','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCD 1a','name' => 'SCD 1a','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCRBD 6','name' => 'SCRBD 6','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCD 1a','name' => 'SCD 1a','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCLBD 3','name' => 'SCLBD 3','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCRBD 7a','name' => 'SCRBD 7a','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCD 1','name' => 'SCD 1','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCD 1 & 1a','name' => 'SCD 1 & 1a','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCD 1 & 1a','name' => 'SCD 1 & 1a','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCLBD 3','name' => 'SCLBD 3','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCD 1 & SCLBD 3','name' => 'SCD 1 & SCLBD 3','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCLBD 3','name' => 'SCLBD 3','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCD 1','name' => 'SCD 1','lokaliti_id' => '27']);
        Blok::create(['code' => 'SCRBD 5','name' => 'SCRBD 5','lokaliti_id' => '27']);
    }
}
