<?php

use Illuminate\Database\Seeder;
use App\Projek;

class ProjekTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Projek::create(['id'=>'1', 'code'=>'CHERMAI', 'name'=>'CHERMAI', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'2', 'code'=>'PADANG BESAR', 'name'=>'PADANG BESAR', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'3', 'code'=>'TELAGA HAJI LATEH', 'name'=>'TELAGA HAJI LATEH', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'4', 'code'=>'TELOK', 'name'=>'TELOK', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'5', 'code'=>'KG. BANAT', 'name'=>'KG. BANAT', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'6', 'code'=>'KG. TITI BESI', 'name'=>'KG. TITI BESI', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'7', 'code'=>'PULAU LINCAI', 'name'=>'PULAU LINCAI', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'8', 'code'=>'BELAT BATU', 'name'=>'BELAT BATU', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'9', 'code'=>'JELEMPOK', 'name'=>'JELEMPOK', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'10', 'code'=>'UTAN KANDIS', 'name'=>'UTAN KANDIS', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'11', 'code'=>'GUAR SANJI', 'name'=>'GUAR SANJI', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'12', 'code'=>'JELAMPOK UTARA', 'name'=>'JELAMPOK UTARA', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'13', 'code'=>'KG BAKONG', 'name'=>'KG BAKONG', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'14', 'code'=>'ALOR BANAT', 'name'=>'ALOR BANAT', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'15', 'code'=>'BEHOR MEMPELAM', 'name'=>'BEHOR MEMPELAM', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'16', 'code'=>'BELAT RAJA', 'name'=>'BELAT RAJA', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'17', 'code'=>'KG. GOBEK', 'name'=>'KG. GOBEK', 'lokaliti_id'=>'1']);
        Projek::create(['id'=>'18', 'code'=>'BEHOR KULIT KERANG', 'name'=>'BEHOR KULIT KERANG', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'19', 'code'=>'BEHOR ROTAN PAHIT', 'name'=>'BEHOR ROTAN PAHIT', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'20', 'code'=>'PERMATANG PAUH TIMUR', 'name'=>'PERMATANG PAUH TIMUR', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'21', 'code'=>'BEHOR LALANG', 'name'=>'BEHOR LALANG', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'22', 'code'=>'PAK LENGAH', 'name'=>'PAK LENGAH', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'23', 'code'=>'KG PELADANG A', 'name'=>'KG PELADANG A', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'24', 'code'=>'KG PELADANG C', 'name'=>'KG PELADANG C', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'25', 'code'=>'BATU 5', 'name'=>'BATU 5', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'26', 'code'=>'BANGSAL LEBAH', 'name'=>'BANGSAL LEBAH', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'27', 'code'=>'TELAGA IDI', 'name'=>'TELAGA IDI', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'28', 'code'=>'KAMPUNG PELADANG B', 'name'=>'KAMPUNG PELADANG B', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'29', 'code'=>'KAMPUNG PELADANG A', 'name'=>'KAMPUNG PELADANG A', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'30', 'code'=>'SG BERAMBANG', 'name'=>'SG BERAMBANG', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'31', 'code'=>'PERMATANG PAUH BARAT', 'name'=>'PERMATANG PAUH BARAT', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'32', 'code'=>'GUNUNG', 'name'=>'GUNUNG', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'33', 'code'=>'BINJAL', 'name'=>'BINJAL', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'34', 'code'=>'MENGKUANG LAYAR', 'name'=>'MENGKUANG LAYAR', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'35', 'code'=>'SG BARU UTAN AJI', 'name'=>'SG BARU UTAN AJI', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'36', 'code'=>'KURUNG TEGAR', 'name'=>'KURUNG TEGAR', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'37', 'code'=>'SURAU', 'name'=>'SURAU', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'38', 'code'=>'SENTANG', 'name'=>'SENTANG', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'39', 'code'=>'BOHOR LATEH', 'name'=>'BOHOR LATEH', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'40', 'code'=>'MENGKUANG LAYAR B', 'name'=>'MENGKUANG LAYAR B', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'41', 'code'=>'TANJUNG GELAM', 'name'=>'TANJUNG GELAM', 'lokaliti_id'=>'2']);
        Projek::create(['id'=>'42', 'code'=>'PANGGAU', 'name'=>'PANGGAU', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'43', 'code'=>'ALOR TOK TERANG', 'name'=>'ALOR TOK TERANG', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'44', 'code'=>'BEHOR GONCHAR', 'name'=>'BEHOR GONCHAR', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'45', 'code'=>'TITI TOK BANDAR', 'name'=>'TITI TOK BANDAR', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'46', 'code'=>'SENA', 'name'=>'SENA', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'47', 'code'=>'KUBANG GAJAH', 'name'=>'KUBANG GAJAH', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'48', 'code'=>'JEJAWI BAKONG', 'name'=>'JEJAWI BAKONG', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'49', 'code'=>'REPOH', 'name'=>'REPOH', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'50', 'code'=>'ALOR REDIS', 'name'=>'ALOR REDIS', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'51', 'code'=>'GUAR SYED ALWI', 'name'=>'GUAR SYED ALWI', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'52', 'code'=>'SG. BAKONG', 'name'=>'SG. BAKONG', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'53', 'code'=>'TELOK EPA', 'name'=>'TELOK EPA', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'54', 'code'=>'GUAR UJUNG BATU', 'name'=>'GUAR UJUNG BATU', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'55', 'code'=>'TOK KUNING', 'name'=>'TOK KUNING', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'56', 'code'=>'BATU HAMPAR', 'name'=>'BATU HAMPAR', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'57', 'code'=>'PADANG PETANI', 'name'=>'PADANG PETANI', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'58', 'code'=>'TANAH TUAKU', 'name'=>'TANAH TUAKU', 'lokaliti_id'=>'3']);
        Projek::create(['id'=>'59', 'code'=>'CHEMUMAR', 'name'=>'CHEMUMAR', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'60', 'code'=>'CIK OK', 'name'=>'CIK OK', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'61', 'code'=>'SG BARU U\/AJI', 'name'=>'SG BARU U\/AJI', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'62', 'code'=>'LONG BOH', 'name'=>'LONG BOH', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'63', 'code'=>'SRI GELAM', 'name'=>'SRI GELAM', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'64', 'code'=>'TAMBUN TULANG', 'name'=>'TAMBUN TULANG', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'65', 'code'=>'PIDA 3', 'name'=>'PIDA 3', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'66', 'code'=>'BEHOR MENTALON', 'name'=>'BEHOR MENTALON', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'67', 'code'=>'LAHAR JAMBU', 'name'=>'LAHAR JAMBU', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'68', 'code'=>'SEMATANG SERDANG', 'name'=>'SEMATANG SERDANG', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'69', 'code'=>'KG TEBOK', 'name'=>'KG TEBOK', 'lokaliti_id'=>'4']);
        Projek::create(['id'=>'70', 'code'=>'BANIR TEMBUS', 'name'=>'BANIR TEMBUS', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'71', 'code'=>'SUNGAI BARU TIMUR', 'name'=>'SUNGAI BARU TIMUR', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'72', 'code'=>'SPG SANGLANG', 'name'=>'SPG SANGLANG', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'73', 'code'=>'PAUH KEPALA BATAS', 'name'=>'PAUH KEPALA BATAS', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'74', 'code'=>'TOK PULAU', 'name'=>'TOK PULAU', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'75', 'code'=>'BONGOR KUDONG', 'name'=>'BONGOR KUDONG', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'76', 'code'=>'PERMATANG BONGOR', 'name'=>'PERMATANG BONGOR', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'77', 'code'=>'PERMATANG KERIANG', 'name'=>'PERMATANG KERIANG', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'78', 'code'=>'BUNGA EMAS', 'name'=>'BUNGA EMAS', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'79', 'code'=>'DATO AHMAD MUSA', 'name'=>'DATO AHMAD MUSA', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'80', 'code'=>'PERMATANG KERIANG (B)', 'name'=>'PERMATANG KERIANG (B)', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'81', 'code'=>'SUNGAI BARU TENGAH', 'name'=>'SUNGAI BARU TENGAH', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'82', 'code'=>'SUNGAI PADANG', 'name'=>'SUNGAI PADANG', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'83', 'code'=>'PAUH TIGA BERADIK', 'name'=>'PAUH TIGA BERADIK', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'84', 'code'=>'??PAUH KEPALA BATAS', 'name'=>'??PAUH KEPALA BATAS', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'85', 'code'=>'PADANG KERIA (B)', 'name'=>'PADANG KERIA (B)', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'86', 'code'=>'BATAS LINTANG', 'name'=>'BATAS LINTANG', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'87', 'code'=>'LAT 1000', 'name'=>'LAT 1000', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'88', 'code'=>'KAMPUNG RAMA', 'name'=>'KAMPUNG RAMA', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'89', 'code'=>'PERMATANG LIMAU MANIS', 'name'=>'PERMATANG LIMAU MANIS', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'90', 'code'=>'PADANG BENTA', 'name'=>'PADANG BENTA', 'lokaliti_id'=>'5']);
        Projek::create(['id'=>'91', 'code'=>'BUKIT HANTU', 'name'=>'BUKIT HANTU', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'92', 'code'=>'PEMATANG KAKA', 'name'=>'PEMATANG KAKA', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'93', 'code'=>'LINDUNGAN BULAN', 'name'=>'LINDUNGAN BULAN', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'94', 'code'=>'PIDA 4', 'name'=>'PIDA 4', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'95', 'code'=>'FIDA 3', 'name'=>'FIDA 3', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'96', 'code'=>'PULAU SIPUTEH', 'name'=>'PULAU SIPUTEH', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'97', 'code'=>'MELELE', 'name'=>'MELELE', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'98', 'code'=>'KODIANG LAMA', 'name'=>'KODIANG LAMA', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'99', 'code'=>'KANDIS', 'name'=>'KANDIS', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'100', 'code'=>'FIDA 5', 'name'=>'FIDA 5', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'101', 'code'=>'MELELE 2', 'name'=>'MELELE 2', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'102', 'code'=>'PADANG SERA', 'name'=>'PADANG SERA', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'103', 'code'=>'KODIANG', 'name'=>'KODIANG', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'104', 'code'=>'MANGGOL BONGOR', 'name'=>'MANGGOL BONGOR', 'lokaliti_id'=>'6']);
        Projek::create(['id'=>'105', 'code'=>'TOK KEPAK PUTAT', 'name'=>'TOK KEPAK PUTAT', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'106', 'code'=>'FIDA 5 PUTAT', 'name'=>'FIDA 5 PUTAT', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'107', 'code'=>'FIDA 6 JERLUN', 'name'=>'FIDA 6 JERLUN', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'108', 'code'=>'PIDA 9 SANGLANG', 'name'=>'PIDA 9 SANGLANG', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'109', 'code'=>'TOK KEPAK AH', 'name'=>'TOK KEPAK AH', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'110', 'code'=>'TITI SELANGOR', 'name'=>'TITI SELANGOR', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'111', 'code'=>'PIDA 3?', 'name'=>'PIDA 3?', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'112', 'code'=>'PIDA 11 SANGLANG', 'name'=>'PIDA 11 SANGLANG', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'113', 'code'=>'PIDA 4', 'name'=>'PIDA 4', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'114', 'code'=>'PIDA 4 PDG PERAHU', 'name'=>'PIDA 4 PDG PERAHU', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'115', 'code'=>'PIDA 3 TUNJANG', 'name'=>'PIDA 3 TUNJANG', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'116', 'code'=>'M\/BONGOR AH', 'name'=>'M\/BONGOR AH', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'117', 'code'=>'M\/BONGOR PUTAT', 'name'=>'M\/BONGOR PUTAT', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'118', 'code'=>'BATU 5 SANGLANG', 'name'=>'BATU 5 SANGLANG', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'119', 'code'=>'PIDA 7 KEPLU', 'name'=>'PIDA 7 KEPLU', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'120', 'code'=>'PIDA 2 NIRAI BATIN', 'name'=>'PIDA 2 NIRAI BATIN', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'121', 'code'=>'PIDA 8 PERING', 'name'=>'PIDA 8 PERING', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'122', 'code'=>'GOLOK PUTTING', 'name'=>'GOLOK PUTTING', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'123', 'code'=>'BATU 4 KEPLU', 'name'=>'BATU 4 KEPLU', 'lokaliti_id'=>'7']);
        Projek::create(['id'=>'124', 'code'=>'LUBUK PINANG SANGLANG', 'name'=>'LUBUK PINANG SANGLANG', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'125', 'code'=>'PADANG GELANGGANG', 'name'=>'PADANG GELANGGANG', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'126', 'code'=>'BATAS BENGKOK', 'name'=>'BATAS BENGKOK', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'127', 'code'=>'LUBUK PINANG JERLUN', 'name'=>'LUBUK PINANG JERLUN', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'128', 'code'=>'LUBUK PINANG AYER HITAM', 'name'=>'LUBUK PINANG AYER HITAM', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'129', 'code'=>'SEMATANG KERPAN', 'name'=>'SEMATANG KERPAN', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'130', 'code'=>'BATU 7\/ PIDA 13 SANGLANG', 'name'=>'BATU 7\/ PIDA 13 SANGLANG', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'131', 'code'=>'MATANG KERENGGA', 'name'=>'MATANG KERENGGA', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'132', 'code'=>'MATANG BONGOR', 'name'=>'MATANG BONGOR', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'133', 'code'=>'TANDOP TANAH', 'name'=>'TANDOP TANAH', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'134', 'code'=>'LANA BULU', 'name'=>'LANA BULU', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'135', 'code'=>'AYER HITAM', 'name'=>'AYER HITAM', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'136', 'code'=>'PIDA 12 SANGLANG', 'name'=>'PIDA 12 SANGLANG', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'137', 'code'=>'PIDA 14', 'name'=>'PIDA 14', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'138', 'code'=>'TANDOP TANAH E', 'name'=>'TANDOP TANAH E', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'139', 'code'=>'LANA BULU JERLUN', 'name'=>'LANA BULU JERLUN', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'140', 'code'=>'BATU 7', 'name'=>'BATU 7', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'141', 'code'=>'KG SANGLANG', 'name'=>'KG SANGLANG', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'142', 'code'=>'BAKAU', 'name'=>'BAKAU', 'lokaliti_id'=>'8']);
        Projek::create(['id'=>'143', 'code'=>'KG KETOL', 'name'=>'KG KETOL', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'144', 'code'=>'PULAU PAK UBIN', 'name'=>'PULAU PAK UBIN', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'145', 'code'=>'PDG SEKOLAH', 'name'=>'PDG SEKOLAH', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'146', 'code'=>'MATANG PINANG', 'name'=>'MATANG PINANG', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'147', 'code'=>'TELAGA BATU PUTAT', 'name'=>'TELAGA BATU PUTAT', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'148', 'code'=>'KG IMAM', 'name'=>'KG IMAM', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'149', 'code'=>'PDG TOK KAYA', 'name'=>'PDG TOK KAYA', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'150', 'code'=>'PIDA 2 JERAM', 'name'=>'PIDA 2 JERAM', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'151', 'code'=>'MAGAT DEWA', 'name'=>'MAGAT DEWA', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'152', 'code'=>'GELONG RAMBAI', 'name'=>'GELONG RAMBAI', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'153', 'code'=>'PIDA 2 TUNJANG', 'name'=>'PIDA 2 TUNJANG', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'154', 'code'=>'PADANG LIMAU', 'name'=>'PADANG LIMAU', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'155', 'code'=>'TOK TAMBAK', 'name'=>'TOK TAMBAK', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'156', 'code'=>'PULAU KAIN', 'name'=>'PULAU KAIN', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'157', 'code'=>'HUTAN SETALI', 'name'=>'HUTAN SETALI', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'158', 'code'=>'PULAU MAHARAJA', 'name'=>'PULAU MAHARAJA', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'159', 'code'=>'KG BAGAN', 'name'=>'KG BAGAN', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'160', 'code'=>'PIDA 2 MEGAT DEWA', 'name'=>'PIDA 2 MEGAT DEWA', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'161', 'code'=>'GUAR TANAH RANG', 'name'=>'GUAR TANAH RANG', 'lokaliti_id'=>'9']);
        Projek::create(['id'=>'162', 'code'=>'SEMATANG GELOK B', 'name'=>'SEMATANG GELOK B', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'163', 'code'=>'SEMATANG KENANG', 'name'=>'SEMATANG KENANG', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'164', 'code'=>'GERBI', 'name'=>'GERBI', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'165', 'code'=>'ALOR BIAK', 'name'=>'ALOR BIAK', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'166', 'code'=>'SEMATANG KONG', 'name'=>'SEMATANG KONG', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'167', 'code'=>'SIMPANG 3', 'name'=>'SIMPANG 3', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'168', 'code'=>'TELOK BINASA', 'name'=>'TELOK BINASA', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'169', 'code'=>'PIDA 4 DELI', 'name'=>'PIDA 4 DELI', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'170', 'code'=>'PIDA 5 ATAS', 'name'=>'PIDA 5 ATAS', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'171', 'code'=>'TELUK TEMPURUNG', 'name'=>'TELUK TEMPURUNG', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'172', 'code'=>'SEMATANG BONGLAI', 'name'=>'SEMATANG BONGLAI', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'173', 'code'=>'KUBANG SEPAT', 'name'=>'KUBANG SEPAT', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'174', 'code'=>'SEBERANG ALOR', 'name'=>'SEBERANG ALOR', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'175', 'code'=>'SMTG GELOK A', 'name'=>'SMTG GELOK A', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'176', 'code'=>'SEMATANG NIBONG', 'name'=>'SEMATANG NIBONG', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'177', 'code'=>'TELOK JUNUS', 'name'=>'TELOK JUNUS', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'178', 'code'=>'KEPALA 20', 'name'=>'KEPALA 20', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'179', 'code'=>'SEMATANG GUNUNG', 'name'=>'SEMATANG GUNUNG', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'180', 'code'=>'TOK PULAU', 'name'=>'TOK PULAU', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'181', 'code'=>'KG BESAR', 'name'=>'KG BESAR', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'182', 'code'=>'KG HUMA', 'name'=>'KG HUMA', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'183', 'code'=>'ALOR BIAK B', 'name'=>'ALOR BIAK B', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'184', 'code'=>'PIDA 5 SEMATANG BONGLAI', 'name'=>'PIDA 5 SEMATANG BONGLAI', 'lokaliti_id'=>'10']);
        Projek::create(['id'=>'185', 'code'=>'SIMPANG 4 KUAR', 'name'=>'SIMPANG 4 KUAR', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'186', 'code'=>'HUTAN SERDANG', 'name'=>'HUTAN SERDANG', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'187', 'code'=>'PADANG LALANG', 'name'=>'PADANG LALANG', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'188', 'code'=>'JERLUN TENGAH', 'name'=>'JERLUN TENGAH', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'189', 'code'=>'TELOK TUI', 'name'=>'TELOK TUI', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'190', 'code'=>'KUBANG NIPAH', 'name'=>'KUBANG NIPAH', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'191', 'code'=>'JERLUN B', 'name'=>'JERLUN B', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'192', 'code'=>'LUBUK AIR', 'name'=>'LUBUK AIR', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'193', 'code'=>'TEMPAYAN PECAH', 'name'=>'TEMPAYAN PECAH', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'194', 'code'=>'KEMBOJA A', 'name'=>'KEMBOJA A', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'195', 'code'=>'KUAR JAWA', 'name'=>'KUAR JAWA', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'196', 'code'=>'MATANG PAKU', 'name'=>'MATANG PAKU', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'197', 'code'=>'SUNGAI DUA', 'name'=>'SUNGAI DUA', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'198', 'code'=>'KUBANG SIAM', 'name'=>'KUBANG SIAM', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'199', 'code'=>'ALOR JANGGUS', 'name'=>'ALOR JANGGUS', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'200', 'code'=>'KUBANG JAWI B', 'name'=>'KUBANG JAWI B', 'lokaliti_id'=>'11']);
        Projek::create(['id'=>'201', 'code'=>'KG RAJA', 'name'=>'KG RAJA', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'202', 'code'=>'TELOK MALEK', 'name'=>'TELOK MALEK', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'203', 'code'=>'PAYA PARIT LATEH', 'name'=>'PAYA PARIT LATEH', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'204', 'code'=>'KG PADANG', 'name'=>'KG PADANG', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'205', 'code'=>'PADANG BAGAN', 'name'=>'PADANG BAGAN', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'206', 'code'=>'PULAU PISANG', 'name'=>'PULAU PISANG', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'207', 'code'=>'PADANG CANGKAT', 'name'=>'PADANG CANGKAT', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'208', 'code'=>'PADANG RIMBA', 'name'=>'PADANG RIMBA', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'209', 'code'=>'ALOR KERIANG', 'name'=>'ALOR KERIANG', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'210', 'code'=>'CHEGAR BARAT', 'name'=>'CHEGAR BARAT', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'211', 'code'=>'PADANG TEMENGGUNG', 'name'=>'PADANG TEMENGGUNG', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'212', 'code'=>'PULAU KETAM', 'name'=>'PULAU KETAM', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'213', 'code'=>'TELOK ARA', 'name'=>'TELOK ARA', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'214', 'code'=>'TELOK MALEK C', 'name'=>'TELOK MALEK C', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'215', 'code'=>'KG TANJUNG', 'name'=>'KG TANJUNG', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'216', 'code'=>'PULAU KECHIK', 'name'=>'PULAU KECHIK', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'217', 'code'=>'PULAU NYIOR', 'name'=>'PULAU NYIOR', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'218', 'code'=>'BOHOR', 'name'=>'BOHOR', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'219', 'code'=>'PULAU TIMBUL', 'name'=>'PULAU TIMBUL', 'lokaliti_id'=>'12']);
        Projek::create(['id'=>'220', 'code'=>'PELUBANG', 'name'=>'PELUBANG', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'221', 'code'=>'PADANG SEJANA', 'name'=>'PADANG SEJANA', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'222', 'code'=>'TELAGA BATU', 'name'=>'TELAGA BATU', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'223', 'code'=>'TITI BESI', 'name'=>'TITI BESI', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'224', 'code'=>'ALOR GANU', 'name'=>'ALOR GANU', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'225', 'code'=>'ALOR MADI', 'name'=>'ALOR MADI', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'226', 'code'=>'SELARONG', 'name'=>'SELARONG', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'227', 'code'=>'MATANG KONG', 'name'=>'MATANG KONG', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'228', 'code'=>'SEBERANG CHEGAR', 'name'=>'SEBERANG CHEGAR', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'229', 'code'=>'PULAU KERENGGA', 'name'=>'PULAU KERENGGA', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'230', 'code'=>'KOTA RENTANG', 'name'=>'KOTA RENTANG', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'231', 'code'=>'ALOR GONCHAR', 'name'=>'ALOR GONCHAR', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'232', 'code'=>'TELOK JAWA', 'name'=>'TELOK JAWA', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'233', 'code'=>'LUBUK KAWAH', 'name'=>'LUBUK KAWAH', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'234', 'code'=>'ALOR RAMBAI', 'name'=>'ALOR RAMBAI', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'235', 'code'=>'ALOR MELINTANG', 'name'=>'ALOR MELINTANG', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'236', 'code'=>'TANJUNG TOK AMIN', 'name'=>'TANJUNG TOK AMIN', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'237', 'code'=>'POKOK LANJUT', 'name'=>'POKOK LANJUT', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'238', 'code'=>'PADANG LALANG', 'name'=>'PADANG LALANG', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'239', 'code'=>'PADANG ZAKAT', 'name'=>'PADANG ZAKAT', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'240', 'code'=>'KUBANG TEDUH', 'name'=>'KUBANG TEDUH', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'241', 'code'=>'SIMPANG TIGA KOTA', 'name'=>'SIMPANG TIGA KOTA', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'242', 'code'=>'KAPALA BENDANG', 'name'=>'KAPALA BENDANG', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'243', 'code'=>'KG PASIR', 'name'=>'KG PASIR', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'244', 'code'=>'BOHOR A', 'name'=>'BOHOR A', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'245', 'code'=>'BOHOR B', 'name'=>'BOHOR B', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'246', 'code'=>'TOK CHENG KOI', 'name'=>'TOK CHENG KOI', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'247', 'code'=>'TOK JALAI', 'name'=>'TOK JALAI', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'248', 'code'=>'KOTA MASJID', 'name'=>'KOTA MASJID', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'249', 'code'=>'TANAH MERAH', 'name'=>'TANAH MERAH', 'lokaliti_id'=>'13']);
        Projek::create(['id'=>'250', 'code'=>'SG BARU SRI GUNUNG', 'name'=>'SG BARU SRI GUNUNG', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'251', 'code'=>'SG BARU GUNUNG A', 'name'=>'SG BARU GUNUNG A', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'252', 'code'=>'SG BARU GUNUNG B', 'name'=>'SG BARU GUNUNG B', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'253', 'code'=>'SG BARU TENGAH A', 'name'=>'SG BARU TENGAH A', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'254', 'code'=>'SG BARU TENGAH B', 'name'=>'SG BARU TENGAH B', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'255', 'code'=>'SG BARU WAWASAN', 'name'=>'SG BARU WAWASAN', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'256', 'code'=>'SG BARU TOK KERAMAT', 'name'=>'SG BARU TOK KERAMAT', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'257', 'code'=>'SEMATANG BOGAK', 'name'=>'SEMATANG BOGAK', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'258', 'code'=>'KG MASJID 4F', 'name'=>'KG MASJID 4F', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'259', 'code'=>'PADANG GARAM', 'name'=>'PADANG GARAM', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'260', 'code'=>'TELOK TALIPON', 'name'=>'TELOK TALIPON', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'261', 'code'=>'MERGONG', 'name'=>'MERGONG', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'262', 'code'=>'KG HILIR', 'name'=>'KG HILIR', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'263', 'code'=>'SUKA MENANTI', 'name'=>'SUKA MENANTI', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'264', 'code'=>'KG BATIN', 'name'=>'KG BATIN', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'265', 'code'=>'SG BARU KUALA SUNGAI', 'name'=>'SG BARU KUALA SUNGAI', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'266', 'code'=>'PADANG PERAK', 'name'=>'PADANG PERAK', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'267', 'code'=>'PARIT BUAYA', 'name'=>'PARIT BUAYA', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'268', 'code'=>'MERGONG B', 'name'=>'MERGONG B', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'269', 'code'=>'LEMPING', 'name'=>'LEMPING', 'lokaliti_id'=>'14']);
        Projek::create(['id'=>'270', 'code'=>'TITI GAJAH A', 'name'=>'TITI GAJAH A', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'271', 'code'=>'TITI BARU', 'name'=>'TITI BARU', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'272', 'code'=>'TITI GAJAH C', 'name'=>'TITI GAJAH C', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'273', 'code'=>'TANJUNG MUSANG A', 'name'=>'TANJUNG MUSANG A', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'274', 'code'=>'TANJUNG MUSANG B', 'name'=>'TANJUNG MUSANG B', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'275', 'code'=>'TELAGA MAS', 'name'=>'TELAGA MAS', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'276', 'code'=>'PADANG HASAN', 'name'=>'PADANG HASAN', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'277', 'code'=>'KUBANG LINTAH', 'name'=>'KUBANG LINTAH', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'278', 'code'=>'ALOR GANDAK', 'name'=>'ALOR GANDAK', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'279', 'code'=>'TITI GAJAH B', 'name'=>'TITI GAJAH B', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'280', 'code'=>'HUTAN KAMPUNG', 'name'=>'HUTAN KAMPUNG', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'281', 'code'=>'HUTAN KANDIS', 'name'=>'HUTAN KANDIS', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'282', 'code'=>'BUKIT PINANG', 'name'=>'BUKIT PINANG', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'283', 'code'=>'BUKIT HANTU', 'name'=>'BUKIT HANTU', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'284', 'code'=>'KG PADANG', 'name'=>'KG PADANG', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'285', 'code'=>'KG MASJID LAMA', 'name'=>'KG MASJID LAMA', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'286', 'code'=>'SEBERANG ALOR', 'name'=>'SEBERANG ALOR', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'287', 'code'=>'LIMBONG', 'name'=>'LIMBONG', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'288', 'code'=>'LENGKUAS', 'name'=>'LENGKUAS', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'289', 'code'=>'ALOR MERAH', 'name'=>'ALOR MERAH', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'290', 'code'=>'LANGGAR', 'name'=>'LANGGAR', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'291', 'code'=>'LEPAI', 'name'=>'LEPAI', 'lokaliti_id'=>'15']);
        Projek::create(['id'=>'292', 'code'=>'PULAU BINJAL', 'name'=>'PULAU BINJAL', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'293', 'code'=>'ALOR MELINTANG\/TOK TEMENGGONG', 'name'=>'ALOR MELINTANG\/TOK TEMENGGONG', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'294', 'code'=>'GERIGIS', 'name'=>'GERIGIS', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'295', 'code'=>'KUBANG MEKKI \/ KG. PETANI', 'name'=>'KUBANG MEKKI \/ KG. PETANI', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'296', 'code'=>'TUALANG 1', 'name'=>'TUALANG 1', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'297', 'code'=>'KUBANG BADAK', 'name'=>'KUBANG BADAK', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'298', 'code'=>'MASJID LAMA', 'name'=>'MASJID LAMA', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'299', 'code'=>'PULAU GELAM', 'name'=>'PULAU GELAM', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'300', 'code'=>'TELOK JAMAT', 'name'=>'TELOK JAMAT', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'301', 'code'=>'TELAGA MASAM', 'name'=>'TELAGA MASAM', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'302', 'code'=>'ALOR KANDANG', 'name'=>'ALOR KANDANG', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'303', 'code'=>'ALOR SEMELA', 'name'=>'ALOR SEMELA', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'304', 'code'=>'PADANG LANGGAR', 'name'=>'PADANG LANGGAR', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'305', 'code'=>'ALOR SETOL', 'name'=>'ALOR SETOL', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'306', 'code'=>'PADANG PETANI', 'name'=>'PADANG PETANI', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'307', 'code'=>'LIMBONG', 'name'=>'LIMBONG', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'308', 'code'=>'ALOR BIDUAN', 'name'=>'ALOR BIDUAN', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'309', 'code'=>'GELAM', 'name'=>'GELAM', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'310', 'code'=>'HUTAN GELAM', 'name'=>'HUTAN GELAM', 'lokaliti_id'=>'16']);
        Projek::create(['id'=>'311', 'code'=>'ALOR SEKAWAN', 'name'=>'ALOR SEKAWAN', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'312', 'code'=>'ALOR BINJAL', 'name'=>'ALOR BINJAL', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'313', 'code'=>'KG. KANDAI', 'name'=>'KG. KANDAI', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'314', 'code'=>'TOK SIBIL', 'name'=>'TOK SIBIL', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'315', 'code'=>'ALOR MENGKUANG', 'name'=>'ALOR MENGKUANG', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'316', 'code'=>'TELOK KANDIH', 'name'=>'TELOK KANDIH', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'317', 'code'=>'KG. RAMBAI', 'name'=>'KG. RAMBAI', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'318', 'code'=>'JELAI', 'name'=>'JELAI', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'319', 'code'=>'ALOR ALI', 'name'=>'ALOR ALI', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'320', 'code'=>'KG RAMBAI TIMUR', 'name'=>'KG RAMBAI TIMUR', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'321', 'code'=>'ALOR MENGKUDU', 'name'=>'ALOR MENGKUDU', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'322', 'code'=>'ALOR GELEGAH', 'name'=>'ALOR GELEGAH', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'323', 'code'=>'KUAR', 'name'=>'KUAR', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'324', 'code'=>'KUBANG JELAI', 'name'=>'KUBANG JELAI', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'325', 'code'=>'ALOR BELAT', 'name'=>'ALOR BELAT', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'326', 'code'=>'ALOR KERIANG', 'name'=>'ALOR KERIANG', 'lokaliti_id'=>'17']);
        Projek::create(['id'=>'327', 'code'=>'KG. SRI PUDAK', 'name'=>'KG. SRI PUDAK', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'328', 'code'=>'ALOR BERALA', 'name'=>'ALOR BERALA', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'329', 'code'=>'KG. NAWA', 'name'=>'KG. NAWA', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'330', 'code'=>'TANAH MERAH', 'name'=>'TANAH MERAH', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'331', 'code'=>'KG. KERKAU', 'name'=>'KG. KERKAU', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'332', 'code'=>'KUALA LANJUT', 'name'=>'KUALA LANJUT', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'333', 'code'=>'CHE KONG\/TOK LA', 'name'=>'CHE KONG\/TOK LA', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'334', 'code'=>'BANGGUL KELING', 'name'=>'BANGGUL KELING', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'335', 'code'=>'ALOR TEBUAN', 'name'=>'ALOR TEBUAN', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'336', 'code'=>'GULAU', 'name'=>'GULAU', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'337', 'code'=>'PERMATANG LIMAU', 'name'=>'PERMATANG LIMAU', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'338', 'code'=>'SG MATI', 'name'=>'SG MATI', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'339', 'code'=>'LUBUK KERIANG', 'name'=>'LUBUK KERIANG', 'lokaliti_id'=>'18']);
        Projek::create(['id'=>'340', 'code'=>'BUKIT RAYA BARAT', 'name'=>'BUKIT RAYA BARAT', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'341', 'code'=>'BUKIT SENI', 'name'=>'BUKIT SENI', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'342', 'code'=>'KUBANG ANAK GAJAH', 'name'=>'KUBANG ANAK GAJAH', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'343', 'code'=>'TEMPOYAK', 'name'=>'TEMPOYAK', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'344', 'code'=>'BUKIT RAYA TIMUR', 'name'=>'BUKIT RAYA TIMUR', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'345', 'code'=>'BATU MENUNGGUL', 'name'=>'BATU MENUNGGUL', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'346', 'code'=>'ALOR PARIT', 'name'=>'ALOR PARIT', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'347', 'code'=>'PAYA SENA', 'name'=>'PAYA SENA', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'348', 'code'=>'BONGGOL MASJID', 'name'=>'BONGGOL MASJID', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'349', 'code'=>'ALOR PARIT BATU 16', 'name'=>'ALOR PARIT BATU 16', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'350', 'code'=>'KG 15 RELONG', 'name'=>'KG 15 RELONG', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'351', 'code'=>'TANJUNG RADIN', 'name'=>'TANJUNG RADIN', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'352', 'code'=>'BUKIT JAMBUL', 'name'=>'BUKIT JAMBUL', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'353', 'code'=>'BUKIT RAYA UTARA', 'name'=>'BUKIT RAYA UTARA', 'lokaliti_id'=>'19']);
        Projek::create(['id'=>'354', 'code'=>'BANGGOL BESI', 'name'=>'BANGGOL BESI', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'355', 'code'=>'KG. PETANI BARAT', 'name'=>'KG. PETANI BARAT', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'356', 'code'=>'KG BANGGOL BASIN', 'name'=>'KG BANGGOL BASIN', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'357', 'code'=>'PAYA KERCHUT', 'name'=>'PAYA KERCHUT', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'358', 'code'=>'PAYA NEDAM', 'name'=>'PAYA NEDAM', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'359', 'code'=>'TANJUNG RADIN', 'name'=>'TANJUNG RADIN', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'360', 'code'=>'KUBANG TEREDEH', 'name'=>'KUBANG TEREDEH', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'361', 'code'=>'MAJAPAHIT', 'name'=>'MAJAPAHIT', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'362', 'code'=>'KG LAHAR BATU', 'name'=>'KG LAHAR BATU', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'363', 'code'=>'CHANGKAT NERING', 'name'=>'CHANGKAT NERING', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'364', 'code'=>'KG LAHAR BUAYA', 'name'=>'KG LAHAR BUAYA', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'365', 'code'=>'KG CHAROK KUDONG', 'name'=>'KG CHAROK KUDONG', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'366', 'code'=>'CHEGAR', 'name'=>'CHEGAR', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'367', 'code'=>'KG KEDAH', 'name'=>'KG KEDAH', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'368', 'code'=>'KG BUKIT KECHIK', 'name'=>'KG BUKIT KECHIK', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'369', 'code'=>'KG BGL TAMBAK', 'name'=>'KG BGL TAMBAK', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'370', 'code'=>'KG GAJAH MATI', 'name'=>'KG GAJAH MATI', 'lokaliti_id'=>'20']);
        Projek::create(['id'=>'371', 'code'=>'PERGAM 1', 'name'=>'PERGAM 1', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'372', 'code'=>'PERGAM 2', 'name'=>'PERGAM 2', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'373', 'code'=>'PERGAM 3', 'name'=>'PERGAM 3', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'374', 'code'=>'ALOR IBUS', 'name'=>'ALOR IBUS', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'375', 'code'=>'TOK TONG', 'name'=>'TOK TONG', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'376', 'code'=>'SEMATANG PINANG', 'name'=>'SEMATANG PINANG', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'377', 'code'=>'SG. PAPAN', 'name'=>'SG. PAPAN', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'378', 'code'=>'TELUK BULANG', 'name'=>'TELUK BULANG', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'379', 'code'=>'ALOR PULAI', 'name'=>'ALOR PULAI', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'380', 'code'=>'SRI PANTAI', 'name'=>'SRI PANTAI', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'381', 'code'=>'ALOR IBUS 2', 'name'=>'ALOR IBUS 2', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'382', 'code'=>'TELOK CHENGAI DALAM', 'name'=>'TELOK CHENGAI DALAM', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'383', 'code'=>'KG PERLIS', 'name'=>'KG PERLIS', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'384', 'code'=>'SEBERANG ALOR', 'name'=>'SEBERANG ALOR', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'385', 'code'=>'SELARONG BATAK', 'name'=>'SELARONG BATAK', 'lokaliti_id'=>'21']);
        Projek::create(['id'=>'386', 'code'=>'KEPALA PARIT', 'name'=>'KEPALA PARIT', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'387', 'code'=>'KERIANG PULAU', 'name'=>'KERIANG PULAU', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'388', 'code'=>'BATU 8,  TOKAI', 'name'=>'BATU 8,  TOKAI', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'389', 'code'=>'SELARONG LALANG', 'name'=>'SELARONG LALANG', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'390', 'code'=>'ALOR BELAT', 'name'=>'ALOR BELAT', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'391', 'code'=>'KEBUN PINANG', 'name'=>'KEBUN PINANG', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'392', 'code'=>'TANDOP', 'name'=>'TANDOP', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'393', 'code'=>'TELUK BAGAN', 'name'=>'TELUK BAGAN', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'394', 'code'=>'KG. BENUA', 'name'=>'KG. BENUA', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'395', 'code'=>'KG. LUAR', 'name'=>'KG. LUAR', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'396', 'code'=>'KG. PADANG', 'name'=>'KG. PADANG', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'397', 'code'=>'SIMPANG EMPAT', 'name'=>'SIMPANG EMPAT', 'lokaliti_id'=>'22']);
        Projek::create(['id'=>'398', 'code'=>'SELARONG PANJANG', 'name'=>'SELARONG PANJANG', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'399', 'code'=>'BATU 8,  SIMPANG EMPAT', 'name'=>'BATU 8,  SIMPANG EMPAT', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'400', 'code'=>'KG PULAI', 'name'=>'KG PULAI', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'401', 'code'=>'BULUH LIMA', 'name'=>'BULUH LIMA', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'402', 'code'=>'KUALA SALA', 'name'=>'KUALA SALA', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'403', 'code'=>'SALA KECHIK', 'name'=>'SALA KECHIK', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'404', 'code'=>'BUKIT CHORAS', 'name'=>'BUKIT CHORAS', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'405', 'code'=>'PERMATANG KANGKONG', 'name'=>'PERMATANG KANGKONG', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'406', 'code'=>'BANGGOL WAN AWANG', 'name'=>'BANGGOL WAN AWANG', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'407', 'code'=>'PADANG JAMBU', 'name'=>'PADANG JAMBU', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'408', 'code'=>'LAHAR KELAMBU', 'name'=>'LAHAR KELAMBU', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'409', 'code'=>'ALOR SERDANG', 'name'=>'ALOR SERDANG', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'410', 'code'=>'PERMATANG IBOS', 'name'=>'PERMATANG IBOS', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'411', 'code'=>'PERPAT', 'name'=>'PERPAT', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'412', 'code'=>'KAMPONG JAWA', 'name'=>'KAMPONG JAWA', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'413', 'code'=>'ALOR BESAR', 'name'=>'ALOR BESAR', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'414', 'code'=>'KG PISANG', 'name'=>'KG PISANG', 'lokaliti_id'=>'23']);
        Projek::create(['id'=>'415', 'code'=>'SG. DAUN TENGAH A', 'name'=>'SG. DAUN TENGAH A', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'416', 'code'=>'ALOR GELENGGANG', 'name'=>'ALOR GELENGGANG', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'417', 'code'=>'GELAM 3', 'name'=>'GELAM 3', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'418', 'code'=>'GELAM 3 KPTE', 'name'=>'GELAM 3 KPTE', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'419', 'code'=>'SG. DEDAP', 'name'=>'SG. DEDAP', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'420', 'code'=>'KUALA SUNGAI DAUN UTARA', 'name'=>'KUALA SUNGAI DAUN UTARA', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'421', 'code'=>'SUNGAI DAUN ATAS', 'name'=>'SUNGAI DAUN ATAS', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'422', 'code'=>'KUALA SUNGAI DAUN SELATAN', 'name'=>'KUALA SUNGAI DAUN SELATAN', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'423', 'code'=>'PERMATANG TEPI LAUT', 'name'=>'PERMATANG TEPI LAUT', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'424', 'code'=>'GELAM 2', 'name'=>'GELAM 2', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'425', 'code'=>'KG BAHAGIA', 'name'=>'KG BAHAGIA', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'426', 'code'=>'PERMATANG BULUH', 'name'=>'PERMATANG BULUH', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'427', 'code'=>'TELUK TAWAR', 'name'=>'TELUK TAWAR', 'lokaliti_id'=>'24']);
        Projek::create(['id'=>'428', 'code'=>'SG BARU DALAM', 'name'=>'SG BARU DALAM', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'429', 'code'=>'KEPALA 20\/30', 'name'=>'KEPALA 20\/30', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'430', 'code'=>'TITI BOM', 'name'=>'TITI BOM', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'431', 'code'=>'BATU 16', 'name'=>'BATU 16', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'432', 'code'=>'BATU 14', 'name'=>'BATU 14', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'433', 'code'=>'BUKIT BESAR', 'name'=>'BUKIT BESAR', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'434', 'code'=>'ALOR KUMBANG', 'name'=>'ALOR KUMBANG', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'435', 'code'=>'SG. BARU LUAR', 'name'=>'SG. BARU LUAR', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'436', 'code'=>'BATU 17', 'name'=>'BATU 17', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'437', 'code'=>'BLOCK 16', 'name'=>'BLOCK 16', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'438', 'code'=>'BATU 11', 'name'=>'BATU 11', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'439', 'code'=>'ALOR NAN', 'name'=>'ALOR NAN', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'440', 'code'=>'BATU 11( P. NYIOR)', 'name'=>'BATU 11( P. NYIOR)', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'441', 'code'=>'PULAU MAS', 'name'=>'PULAU MAS', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'442', 'code'=>'BATU 15', 'name'=>'BATU 15', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'443', 'code'=>'KOBAH', 'name'=>'KOBAH', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'444', 'code'=>'PADANG BESAR', 'name'=>'PADANG BESAR', 'lokaliti_id'=>'25']);
        Projek::create(['id'=>'445', 'code'=>'ULU SEDAKA', 'name'=>'ULU SEDAKA', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'446', 'code'=>'KG GELAM', 'name'=>'KG GELAM', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'447', 'code'=>'SUNGAI TONGKANG', 'name'=>'SUNGAI TONGKANG', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'448', 'code'=>'SUNGAI KERING', 'name'=>'SUNGAI KERING', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'449', 'code'=>'BATU 17 (MODEL FARM)', 'name'=>'BATU 17 (MODEL FARM)', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'450', 'code'=>'SUNGAI BUJUR', 'name'=>'SUNGAI BUJUR', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'451', 'code'=>'SG LINTANG', 'name'=>'SG LINTANG', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'452', 'code'=>'BATAS BARU', 'name'=>'BATAS BARU', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'453', 'code'=>'KUBANG PASU', 'name'=>'KUBANG PASU', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'454', 'code'=>'KUALA SEDAKA', 'name'=>'KUALA SEDAKA', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'455', 'code'=>'SELENGKOH TENGAH', 'name'=>'SELENGKOH TENGAH', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'456', 'code'=>'SELENGKOH', 'name'=>'SELENGKOH', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'457', 'code'=>'KABU 10', 'name'=>'KABU 10', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'458', 'code'=>'SG LIMAU DALAM', 'name'=>'SG LIMAU DALAM', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'459', 'code'=>'KUALA SG LIMAU', 'name'=>'KUALA SG LIMAU', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'460', 'code'=>'PADANG LUMAT', 'name'=>'PADANG LUMAT', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'461', 'code'=>'PULAU TEMBUN', 'name'=>'PULAU TEMBUN', 'lokaliti_id'=>'26']);
        Projek::create(['id'=>'462', 'code'=>'DULANG KECHIL', 'name'=>'DULANG KECHIL', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'463', 'code'=>'KUALA DULANG BESAR', 'name'=>'KUALA DULANG BESAR', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'464', 'code'=>'TITI BATU', 'name'=>'TITI BATU', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'465', 'code'=>'SUNGAI YAN', 'name'=>'SUNGAI YAN', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'466', 'code'=>'KAMPUNG PERIGI', 'name'=>'KAMPUNG PERIGI', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'467', 'code'=>'SUNGAI LINTANG', 'name'=>'SUNGAI LINTANG', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'468', 'code'=>'BATU 22', 'name'=>'BATU 22', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'469', 'code'=>'DULANG TENGAH', 'name'=>'DULANG TENGAH', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'470', 'code'=>'DULANG BESAR', 'name'=>'DULANG BESAR', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'471', 'code'=>'TITI TERAS', 'name'=>'TITI TERAS', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'472', 'code'=>'GUAR CHEMPEDAK', 'name'=>'GUAR CHEMPEDAK', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'473', 'code'=>'PERUPOK', 'name'=>'PERUPOK', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'474', 'code'=>'ULU DULANG', 'name'=>'ULU DULANG', 'lokaliti_id'=>'27']);
        Projek::create(['id'=>'475', 'code'=>'BATU 17', 'name'=>'BATU 17', 'lokaliti_id'=>'27']);

    }
}
